### ISSUE TITLE
AWS IAM resources to v1beta1

### ISSUE THREAD

**Issue by prasek** [crossplane/provider-aws#100]
### What problem are you facing?
We would like all existing v1alpha1 Crossplane IAM resources to be bumped to v1beta1 quality.

### How could Crossplane help solve your problem?
Move IAM resources to v1beta1 standards

### References
* https://crossplane.io/docs/v0.8/api/crossplaneio/stack-aws/identity-aws-crossplane-io-v1alpha3.html

**Comment by infinitecompute** [comment]
Separated networking and VPC into [#145](https://github.com/crossplane/stack-aws/issues/145) for easier tracking.

**Comment by hasheddan** [comment]
Ref #141

**Comment by infinitecompute** [comment]
Apparently this didn't get linked to the PR: https://github.com/crossplane/provider-aws/pull/141
PR has been merged, closing this.
