### ISSUE TITLE
The controller fails to create a glue crawler on AWS

### ISSUE THREAD

**Issue by nimakaviani** [crossplane/provider-aws#1018]
### What happened?

With crossplane version `1.6.0-rc.0.99.g1f840122` and `provider-aws@@v0.21.2`, for a sample glue crawler resource like the following:

```yalm
apiVersion: glue.aws.crossplane.io/v1alpha1
kind: Crawler
metadata:
  name: glue-crawler-crossplane
spec:
  forProvider:
    databaseName: glue-db-crossplane
    region: us-west-2
    roleArn: crawler-role-crossplane
    targets:
      s3Targets:
      - path: s3://my-bucket/etl-outputs/user/
  providerRef:
    name: provider-aws
  providerConfigRef:
    name: default
  deletionPolicy: Delete
```

the controller fails to create the resource first time around, with the following error message:

```
Events:
  Type     Reason                        Age                    From                                    Message
  ----     ------                        ----                   ----                                    -------
  Warning  CannotCreateExternalResource  80s (x442 over 3h31m)  managed/crawler.glue.aws.crossplane.io  cannot create Crawler in AWS: InvalidParameter: 1 validation error(s) found.
- missing required field, CreateCrawlerInput.Name.
```

### How can we reproduce it?
The above resource should reproduce the issue, given that you have a glue database and the relevant IAM role defined.

### Potential root cause?

Looking at how the `CrawlerInput` name is populated for the glue crawler in `preCreate`, it appears that it is done by pulling the value from the `ExternalName` in the resource metadata [here](https://github.com/crossplane/provider-aws/blob/79762cf4b9df03bac1bba6a33c902f5c283926a8/pkg/controller/glue/crawler/setup.go#L82).

This basically means that the resource needs to have the annotation `crossplane.io/external-name` set to the resource name, for `preCreate` to populate the name in the request input. This is inconsistent with how other glue resources are created with their names coming from `metadata.name`.

I tried adding the annotation to my resource like the following, and the controller successfully created the resource on AWS infra:

```yalm
apiVersion: glue.aws.crossplane.io/v1alpha1
kind: Crawler
metadata:
  name: glue-crawler-crossplane
  annotations:
    crossplane.io/external-name: glue-crawler-crossplane
...
```

**Comment by haarchri** [comment]
as followup for #992 i opened #1019 we missed to cleanup https://github.com/crossplane/provider-aws/pull/1019/files#diff-4bb16b94fe7d5c93088d9a4acadf090dde1b4cc4a168ebc08e5d074dd8f2131bL56 so the external-name is published
