### ISSUE TITLE
`Subnet` fails with InvalidParameterValue for availabilityZone in other than "us-east-1" region.

### ISSUE THREAD

**Issue by jaroslav-fedor-swi** [crossplane/provider-aws#1048]
### What happened?
A `Subnet` with following configuration:
```
    availabilityZone: us-west-2c
```
 and `VPC`:
```
    region: us-west-2
```

results in:

```
    Message:               create failed: failed to create the Subnet resource: api error InvalidPara
meterValue: Value (us-west-2c) for parameter availabilityZone is invalid. Subnets can currently only
be created in the following availability zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-ea
st-1e, us-east-1f.
```
### How can we reproduce it?
Create `VPC` and `Subnet` in region different to `us-east-1`.

### What environment did it happen in?
Crossplane version: 

`provider-aws@v0.22.0`

**Comment by haarchri** [comment]
@jaroslav-fedor-swi did you set region &  availabilityZone for Subnet ? https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/Subnet/v1beta1@v0.22.0#spec-forProvider-region

**Comment by jaroslav-fedor-swi** [comment]
@haarchri Adding `region` helped! Thanks. I think it should be mentioned for `availabilityZone` doc.

**Comment by haarchri** [comment]
Thanks for Feedback - think we have the same documentation then the GO SDK ;)
