### ISSUE TITLE
Release v0.24.0 on February 10, 2022

### ISSUE THREAD

**Issue by haarchri** [crossplane/provider-aws#1061]
In accordance with [release policy](https://github.com/crossplane/provider-aws#releases).

### Checklist

* [x] Create the new release branch with minor version, i.e. `release-0.24` for `v0.24.0`.
  * You can use the existing branch for patch releases.
* [x] Tag release by running `Tag` action in Github UI against release branch, i.e. `release-X` branch.
  * Use v-prefixed version, like `v0.24.0`, for both description and tag.
* [x] Run `CI` action against release branch.
* [x] Tag the next pre-release by running `Tag` action in Github UI against `master` branch, if it's not a patch release.
  * The tag should be `v0.25.0-rc.0` if you're releasing `v0.24.x`.
* [x] Validate that you can install the published version, basic sanity check.
* [x] Run `Promote` action to promote it in `alpha` channel if it's pre-`1.0`.
* [x] Use Github UI to generate release notes.
  * Make sure to scan all PRs marked with `breaking-change` and add instructions for users to handle them.
* [x] Create the next release issue with a title that has its date, **4 weeks** after the current release day.
* [x] Announce in Slack, Twitter etc.

**Comment by muvaf** [comment]
I've got some changes ready and plated for this release that bump versions of some of the resources to v1beta1, which can't be done in a patch release even though they don't possess any risk [[1]](https://github.com/crossplane/provider-aws/pull/1123) [[2]](https://github.com/crossplane/provider-aws/pull/1107). But I'm on PTO that day. We have synced with @haarchri to postpone the release for 1 day, i.e. on February 10th. Please do chime in if that doesn't work for anyone.

**Comment by muvaf** [comment]
v0.24.0 has been cut on Feb 10, I'll publish the release notes today.

**Comment by muvaf** [comment]
Done https://github.com/crossplane/provider-aws/releases/tag/v0.24.1
