### ISSUE TITLE
EKS Addon: IsUpToDate loop does not work as expected

### ISSUE THREAD

**Issue by MisterMX** [crossplane/provider-aws#1070]
### What happened?

The `isUpToDate` function does not work as the result is always true (i.e. different `AddonVersion`).

The referred line: https://github.com/crossplane/provider-aws/blob/96a15aa76c5060da9769605acb4a3824ec521d0f/pkg/controller/eks/addon/setup.go#L133

### What environment did it happen in?

Current master (96a15aa76c5060da9769605acb4a3824ec521d0f)

**Comment by haarchri** [comment]
fixed & implemented via https://github.com/crossplane/provider-aws/pull/1068
