### ISSUE TITLE
SNS Topic and Subscription to be generated and bumped to v1beta1

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#1109]
### What problem are you facing?

We have `SNSTopic` and `SNSSubscription` resources in `notification` group and they are manually implemented. We'd like to bump them to v1beta1, hence they need to be renamed https://github.com/crossplane/provider-aws/issues/340 and we should port them to be generated by copying the parts that are still relative after moving to code generation pipeline

### How could Crossplane help solve your problem?

Implement these two resources using ACK and copy the special logic parts. I think we should mark existing `SNSTopic` and `SNSSubscription` resources as deprecated with kubebuilder tags but not take action for now since we're too close to the next release and there might be schema differences which would make it hard to migrate for people.

**Comment by domingusj** [comment]
As part of this rename could the functionality for FIFO topics and the content-based deduplication setting also be added?

https://docs.aws.amazon.com/sns/latest/dg/fifo-message-dedup.html

The `provider-jet-aws` has these settings for reference: 

- https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/sns.aws.jet.crossplane.io/Topic/v1alpha1@v0.4.0-preview#spec-forProvider-fifoTopic

- https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/sns.aws.jet.crossplane.io/Topic/v1alpha1@v0.4.0-preview#spec-forProvider-contentBasedDeduplication

I'd be happy to help get these added but not sure how to get started. Thank you for your efforts on crossplane!

**Comment by muvaf** [comment]
Yes, if they are part of the main model in ACK. If not though, I think we'll try to get the same functionality ported over to keep the issue scoped and then open issues for these settings to be added later. @ezgidemirel would have more details and make the decision.

**Comment by ezgidemirel** [comment]
Hi @domingusj, we couldn't move resources to ACK due to some problems we encountered with code-generator. Therefore, missing functionalities are not added automatically. Could you please open another issue for that? Thanks!

**Comment by domingusj** [comment]
Thanks @ezgidemirel , opened a new issue here: https://github.com/crossplane/provider-aws/issues/1139
