### ISSUE TITLE
EKS Cluster credentials expiration

### ISSUE THREAD

**Issue by lukeweber** [crossplane/provider-aws#111]
Credentials in EKS are based on creating a token that has a max life of 15 minutes. We need to consider whether we should be integrating at kubeconfig credentials, instead of ClientConfig(token,CA). 

The kubeconfig integration would have the baggage of supporting gcloud auth, and aws iam authenticator binaries.

Alternatively, we could likely create service accounts that were long lived for the same purpose, but this seems less ideal.

**Comment by hasheddan** [comment]
@negz can we close this with continuous secret propagation?

**Comment by haarchri** [comment]
@lukeweber  we renew the secret in every reconcile loop - close the issue - feel free to reopen if we have problems with this implementation
