### ISSUE TITLE
SNS - Add support for FIFO topics and content-based deduplication setting

### ISSUE THREAD

**Issue by domingusj** [crossplane/provider-aws#1139]
### What resource do you need?

It is not currently possible to enable the FIFO or content-based deduplication settings for SNS Topics.

Docs:

https://docs.aws.amazon.com/sns/latest/dg/fifo-message-dedup.html

The provider-jet-aws has these settings for reference:

https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/sns.aws.jet.crossplane.io/Topic/v1alpha1@v0.4.0-preview#spec-forProvider-fifoTopic

https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/sns.aws.jet.crossplane.io/Topic/v1alpha1@v0.4.0-preview#spec-forProvider-contentBasedDeduplication

### What is your use case?
Creating and configuring FIFO SNS topics using crossplane.

**Comment by tkaesserfm** [comment]
This would be really great to have
