### ISSUE TITLE
Release v0.25.0 on March 11, 2022

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#1142]
### Checklist

* [x] Create the new release branch with minor version, i.e. `release-0.25` for `v0.25.0`.
  * You can use the existing branch for patch releases.
* [x] Tag release by running `Tag` action in Github UI against release branch, i.e. `release-X` branch.
  * Use v-prefixed version, like `v0.25.0`, for both description and tag.
* [x] Run `CI` action against release branch.
* [x] Tag the next pre-release by running `Tag` action in Github UI against `master` branch, if it's not a patch release.
  * The tag should be `v0.26.0-rc.0` if you're releasing `v0.25.x`.
* [x] Validate that you can install the published version, basic sanity check.
* [x] Run `Promote` action to promote it in `alpha` channel if it's pre-`1.0`.
* [x] Use Github UI to generate release notes.
  * Make sure to scan all PRs marked with `breaking-change` and add instructions for users to handle them.
* [x] Create the next release issue with a title that has its date, **4 weeks** after the current release day.
* [x] Announce in Slack, Twitter etc.

**Comment by haarchri** [comment]
We have synced with @chlunde  and @muvaf to postpone the release for 2 days, i.e. on March 11th. To get a fix for RDS in the Release (https://github.com/crossplane/provider-aws/pull/971)  Please do chime in if that doesn't work for anyone.

**Comment by muvaf** [comment]
@haarchri seems like https://github.com/crossplane/provider-aws/pull/971 got merged. In order not to block the master branch, I'm cutting the release branch now.

**Comment by haarchri** [comment]
If you have time you can release ;)

**Comment by muvaf** [comment]
Let's do it on March 11th since that's the date communicated in the earlier comment.

**Comment by haarchri** [comment]
tested the upgrade from provider-aws v0.24.1 to v0.25.0 

```
kubectl get pkgrev
NAME                                                              HEALTHY   REVISION   IMAGE                             STATE      DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/crossplane-aws-bec8ce984e49    True      2          crossplane/provider-aws:v0.25.0   Active                                 9m25s
providerrevision.pkg.crossplane.io/crossplane-aws-f78664a342f1    True      1          crossplane/provider-aws:v0.24.1   Inactive                               67m
                          8m30s
```

**Comment by haarchri** [comment]
checked all new crds

```
groups.cognitoidentityprovider.aws.crossplane.io                2022-03-11T12:05:47Z
identityproviders.cognitoidentityprovider.aws.crossplane.io     2022-03-11T12:05:37Z
userpoolclients.cognitoidentityprovider.aws.crossplane.io       2022-03-11T12:05:42Z
userpooldomains.cognitoidentityprovider.aws.crossplane.io       2022-03-11T12:05:44Z
userpools.cognitoidentityprovider.aws.crossplane.io             2022-03-11T12:05:47Z
domains.cloudsearch.aws.crossplane.io                           2022-03-11T12:05:51Z
workspaces.prometheusservice.aws.crossplane.io                  2022-03-11T12:05:51Z
instanceprofiles.iam.aws.crossplane.io                          2022-03-11T12:05:35Z
dbinstanceroleassociations.rds.aws.crossplane.io                2022-03-11T12:05:42Z
```
