### ISSUE TITLE
DocDB docs are wrong for description

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#1144]
### What happened?

Could not create a DocDB subnet group because the DBSubnetGroup said I needed `dbSubnetGroupDescription` but the docs said I needed `description`.  

The CRD said this is the correct way to set the description:

```
"dbSubnetGroupDescription": {
  "description": "The description for the subnet group.",
  "type": "string"
},
```

### How can we reproduce it?

Make a subnet group for docdb with the key description in forProvider based on these docs: https://doc.crds.dev/github.com/crossplane/provider-aws/database.aws.crossplane.io/DBSubnetGroup/v1beta1@v0.23.0

### What environment did it happen in?
Crossplane version:

**Comment by kferrone** [comment]
I just came across another inconsistency with the same docs on the DocDB subnet groups. 

Docs say the subnet selector is `subnetIdSelector` but the CRD says it is `subnetIDsSelector`.

**Comment by haarchri** [comment]
@MisterMX can you assist ?

**Comment by haarchri** [comment]
@kferrone  please check the correct link for DocDB: https://doc.crds.dev/github.com/crossplane/provider-aws/docdb.aws.crossplane.io/DBSubnetGroup/v1alpha1@v0.23.0
 or
https://doc.crds.dev/github.com/crossplane/provider-aws/docdb.aws.crossplane.io/DBSubnetGroup/v1alpha1@v0.23.0


you referenced a link a for database resource

**Comment by kferrone** [comment]
Oh shoot you're right, my bad. I think I've been moving too fast and making dumb mistakes.
