### ISSUE TITLE
Pass Domain through on EKS Provision for Route53 Permissions

### ISSUE THREAD

**Issue by lukeweber** [crossplane/provider-aws#115]
When we provision an EKS cluster, we create a Route53NodeInstancePolicy in our cloudformation script that allows full access from the node to administer the route53 records.
See: https://github.com/crossplaneio/crossplane/blob/3bc975537fe11b104779c0deac5d57ed8bf53bd2/pkg/clients/aws/eks/eks.go#L252

Note configuration notes here:
https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/aws.md

We should improve the security model by limiting to the domain that cluster should operate on:
1. Pass domain name through from claim
1. Resolve domain name to actual hosted zone id
1. Pass hosted zone id to cloudformation script in eks.go client to limit scope of permissions in aws role.

**Comment by muvaf** [comment]
Not relevant anymore.
