### ISSUE TITLE
Support Backup or Retention period for AWS DB instances

### ISSUE THREAD

**Issue by SachinHg** [crossplane/provider-aws#116]
**Is this a bug report or feature request?**
 Feature Request

**What should the feature do:**
The feature should allow the admins to let users specify a backup/retention period for AWS RDS DB instances.
**What is use case behind this feature:**
I would like to backup my data stored on the DB instance for recovery.

**Environment**:

AWS

**Comment by negz** [comment]
@SachinHg have you taken a look at our new v1beta1 RDS instances? I believe they support everything RDS supports, so you should be able to configure a backup and retention period.

**Comment by negz** [comment]
Hi @SachinHg, I'm going to mark this as resolved, as I believe we now support this. Please let me know if that's not the case.
