### ISSUE TITLE
generic name for AWS provider ServiceAccount to generate IRSA upfront via IaC (for example Terraform)

### ISSUE THREAD

**Issue by youwalther65** [crossplane/provider-aws#1172]
### What problem are you facing?
I am suing Terraform for initial creation of (master) EKS cluster. I noticed that adding AWS proivder the corresponding ServiceAccount is created and uses a random number as a suffix. This make sit impossible to create IRSA upfront,
My workflow is as follows

Terraform:
- create cluster
- create IRSA related stuff
- Fluxv2 bootstrap cluster

Fluxv2
- install crossplane via Helm chart via HelmRelease resource
- install AWS provider via Kustomization 

### How could Crossplane help solve your problem?
If we have a hard-coded AWS provider SA name I can create the corresponding IAM role with correct trust policy upfront in Terraform. Then crossplane AWS provider could pickup this IAM role and creates the SA annotating it with the role ARN.

**Comment by haarchri** [comment]
You can set StringLike Wildcard *

```

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "${OIDC_PROVIDER}:sub": "system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:provider-aws-*"
        }
      }
    }
  ]
}
EOF
```

**Comment by haarchri** [comment]
Check also our Guide here https://github.com/crossplane/provider-aws/blob/master/AUTHENTICATION.md

**Comment by maxstepanov** [comment]
@haarchri I have followed the AUTHENTICATION.md and `provider-aws-*` wildcard doesn't work. I've wasted quite a lot of time on this sadly. I don't use eksctl but have terraform module that all other irsa are generated with. Only setting the exact service account with generation number works otherwise provider-aws is unable to assume the identity. `*` doesn't work either.

**Comment by haarchri** [comment]
You need to use StringLike

**Comment by maxstepanov** [comment]
🐼 🤦
