### ISSUE TITLE
Support EFS Access Points

### ISSUE THREAD

**Issue by zonybob** [crossplane/provider-aws#1182]
### What resource do you need?
Would like to have Crossplane provision and manage EFS Access Points

### What is your use case?
I intend to make a composition which bundles a single PersistentVolume (PV) with an Access Point (at a certain path/directory). I already have a separate composition that manages a `FileSystem` and `MountTarget` so I'd like the Access Point to be able to use selectors to gather that FileSystemID by labels.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?

I have reached out on Slack and it seems that this feature shouldn't be a stretch to implement. I am willing to contribute it.

**Comment by haarchri** [comment]
hey @zonybob  think you can simple remove this entry https://github.com/crossplane/provider-aws/blob/master/apis/efs/generator-config.yaml#L3 and lets generate the resource and implement like documentation in https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md

**Comment by EdgeJ** [comment]
@zonybob I started playing around with this before seeing that there was an open issue here. I have a working setup on my machine that I can PR for this, unless you prefer to tackle it yourself. Just let me know.

**Comment by zonybob** [comment]
@EdgeJ actually this sounds great! I am scrambling to find the time for this, so this will be a big help. I'd be glad to help review the PR and test it out to make sure it works out for my use case if you don't mind.
