### ISSUE TITLE
DAX Cluster Support

### ISSUE THREAD

**Issue by DanielTemesgen** [crossplane/provider-aws#1195]
### What problem are you facing?

Would be nice to have DAX cluster Support within provider-aws, to complement the existing DynamoDB CRDs.
### How could Crossplane help solve your problem?

Add a CRD to create/manage DAX Clusters.

**Comment by haarchri** [comment]
@DanielTemesgen  thanks for this enhancement - did you have time to create a PR ? 
please check: https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md

our code-generator can generate dax resources like cluter, parameter_group, subnet_group
<img width="469" alt="image" src="https://user-images.githubusercontent.com/21083497/157498033-16d821ce-1930-4296-8486-331f32249a31.png">

**Comment by DanielTemesgen** [comment]
@haarchri thanks for the reply
sure, I'll have a try

**Comment by DanielTemesgen** [comment]
Hi @haarchri, could you please approve the workflow in the linked PR?
