### ISSUE TITLE
Code generation breaks on generating sfn controllers

### ISSUE THREAD

**Issue by EdgeJ** [crossplane/provider-aws#1198]
### What happened?

When running `make generate`, the process fails when generating sfn resources, printing the following message:
```
13:51:15 [ .. ] Generating sfn controllers and CRDs
Error: open /Users/jedge/.cache/ack-generate/src/aws-sdk-go/models/apis/service-quotas/2019-06-24/api-2.json: too many open files
exit status 1
make[2]: *** [services] Error 1
make[1]: *** [services.all] Error 2
make: *** [generate] Error 2
```

Renaming or deleting the `apis/sfn/generator-config.yaml` file to remove it from the generate resources list and running `make generate` again works.

### What environment did it happen in?
macOS 12.2.1
golang v1.17.6

**Comment by haarchri** [comment]
@EdgeJ see this also on my mac can you try `ulimit -n 10240` Default is `256`

**Comment by EdgeJ** [comment]
Ugh. I should have tried that. Thanks @haarchri. I hadn't considered this because I have run into the same error message before for legitimate problems (code generator config referenced incorrect AWS service names).
