### ISSUE TITLE
Support for user-defined tags for s3 buckets

### ISSUE THREAD

**Issue by rberrelleza** [crossplane/provider-aws#122]
### What problem are you facing?
When creating an s3 bucket, I'd like it to be created with certain tags to help identify the owner, when it was created, the department, cost center, etc...

### How could Crossplane help solve your problem?
I'd be useful if I could specify tags in the YAML I use when claiming an S3 bucket. Maybe in https://crossplaneio.github.io/docs/v0.7/api/crossplaneio/stack-aws/storage-aws-crossplane-io-v1alpha3.html#S3BucketParameters ?

**Comment by hasheddan** [comment]
@rberrelleza thanks for opening this issue! I have moved it to this repo to it can be tracked closer to the source :+1:

**Comment by janwillies** [comment]
it would be nice to have tags everywhere, at minimum the original kubernetes namespace

**Comment by kelvinwijaya** [comment]
Hi @hasheddan ,

Would like to know if i can work on adding the tagging support in S3Bucket v1alpha3 api? 

The api will be based on following: https://github.com/aws/aws-sdk-go-v2/blob/master/service/s3/api_op_PutBucketTagging.go

**Comment by muvaf** [comment]
Hi @kelvinwijaya . I have created a few commits for v1beta1 Buckets and handed off to @krishchow and he's working on it right now. So, I suspect that your PRs could land around the same time and yours may not get merged. So, it's up to you. I'd be happy to merge your PR but it will probably be removed before the release.

**Comment by kelvinwijaya** [comment]
Hi @muvaf . Thanks! I actually have done the changes, just that pending to test. Understand that the v1beta1 has been WIP by @krishchow , it could help on the tagging feature to be propagated into the next version.

Btw, I have issue after pulling the latest master branch for provider-aws, I didn't face any build issue last friday but when i pull the latest code today, got the following:

```
angryjet: error: error loading packages using pattern ./...: /Users/kelvinwijaya/go/src/github.com/kelvinwijaya/provider-aws/apis/ec2/v1alpha1/zz_generated.managedlist.go:27:14: cannot use &l.Items[i] (value of type *ElasticIP) as resource.Managed value in assignment: missing method GetDeletionPolicy
```

**Comment by muvaf** [comment]
@kelvinwijaya That issue seems to be caused because of my recent update of crossplane-runtime dependency. ElasticIP has been implemented while that update was still an open PR. This PR should fix that problem: https://github.com/crossplane/provider-aws/pull/324

**Comment by kelvinwijaya** [comment]
Hi @muvaf . I have open a PR for the changes #328 

I am not sure why my e2e test failed, but when i run it locally i have no issues and the test passed

**Comment by muvaf** [comment]
Fixed by https://github.com/crossplane/provider-aws/pull/328
