### ISSUE TITLE
aws provider authentication - allow IAM user to assume role

### ISSUE THREAD

**Issue by brianmjones** [crossplane/provider-aws#1229]
### What problem are you facing?

Currently the only way to assume a role in the ProviderConfig is to use Injected Identity.  We would like to use an IAM user and assume a role.

Currently the ProviderConfig looks like this for the Injected Identity and assume role feature.

$ cat <<EOF | kubectl apply -f -
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: account-b
spec:
  assumeRoleARN: "arn:aws:iam::999999999999:role/account-b"
  credentials:
    **source: InjectedIdentity**
EOF

### How could Crossplane help solve your problem?

Allow the ProviderConfig to use IAM user credentials when assuming a role...  i.e.

$ cat <<EOF | kubectl apply -f -
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: account-b
spec:
  assumeRoleARN: "arn:aws:iam::999999999999:role/account-b"
  credentials:
    **assumeRoleARN: "arn:aws:iam::999999999999:role/account-b"
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds**
EOF

**Comment by haarchri** [comment]
@brianmjones thanks for opening - think we have a Lack of documentation - in general this is possible checkout my original PR https://github.com/crossplane/provider-aws/pull/912

**Comment by brianmjones** [comment]
ok, that would be awesome... I'll give it a try and close the issue once verified

**Comment by haarchri** [comment]
Would be great If you have time to enhance the documentation ;)
