### ISSUE TITLE
EKS Generating Invalid Secret

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#1247]
### What happened?

I migrated my EKS resources from one cluster to another cluster. Everything seems to work except the WriteConnectionSecrretToRef wrote a secret with invalid credentials???
Why and How is Crossplane generating the wrong kubeconfig??? Anything I can do to fix this issue?

### How can we reproduce it?

Copy yamls of an EKS cluster to another Another EKS cluster with Crossplane installed. Try using the generated secret for the EKS cluster. 

### What environment did it happen in?
Crossplane version: 1.7.0
EKS 1.2
Provider AWS - v0.25.0

**Comment by haarchri** [comment]
could be related to https://github.com/crossplane/provider-aws/issues/1010
