### ISSUE TITLE
Failed to query Bucket: api error MovedPermanently

### ISSUE THREAD

**Issue by TheMatrix97** [crossplane/provider-aws#1252]
### What happened?
Hi!, I'm trying to deploy a S3 following the crossplane install documentation, but when instantiating an S3 bucket I'm getting the following error:
```bash
Warning  CannotObserveExternalResource  18s (x14 over 12m)  managed/bucket.s3.aws.crossplane.io  failed to query Bucket: api error MovedPermanently: Moved Permanently
```

### How can we reproduce it?
Install crossplane with the getting started configuration
````bash
kubectl crossplane install configuration registry.upbound.io/xp/getting-started-with-aws:v1.7.0;

AWS_PROFILE=default && echo -e "[default]\naws_access_key_id = $(aws configure get aws_access_key_id --profile $AWS_PROFILE)\naws_secret_access_key = $(aws configure get aws_secret_access_key --profile $AWS_PROFILE)" > creds.conf;

kubectl create secret generic aws-creds -n crossplane-system --from-file=creds=./creds.conf

kubectl apply -f https://raw.githubusercontent.com/crossplane/crossplane/release-1.7/docs/snippets/configure/aws/providerconfig.yaml
````
The installation seems it's fine, the provider is returning a healthy status:
````bash
NAME                      INSTALLED   HEALTHY   PACKAGE                           AGE
crossplane-provider-aws   True        True      crossplane/provider-aws:v0.25.0   20m
````
Finally, try to create an S3 Bucket applying the following manifest:
````yaml
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: buckettest
spec:
  providerConfigRef:
    name: default
  forProvider:
    locationConstraint: eu-central-1
````
It returns the error described before at the beginning

### What environment did it happen in?
Crossplane version: 1.7.0
Aws provider 0.25.0

I'm using docker-desktop Kubernetes instance with the following version:
````bash
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
````

Thanks!

**Comment by TheMatrix97** [comment]
Just to followup, I tried to deploy the basic RDS instance showed in the documentation (kubectl apply -f https://raw.githubusercontent.com/crossplane/crossplane/release-1.7/docs/snippets/configure/aws/providerconfig.yaml) and worked like charm, seems it's something related with S3 CRD itself

**Comment by haarchri** [comment]
@TheMatrix97 we using the return/message from go-sdk

**Comment by haarchri** [comment]
@TheMatrix97 we using the return/message from go-sdk
