### ISSUE TITLE
Release v0.27.0 on May 04, 2022

### ISSUE THREAD

**Issue by haarchri** [crossplane/provider-aws#1264]
### Checklist

* [x] Create the new release branch with minor version, i.e. `release-0.27` for `v0.27.0`.
  * You can use the existing branch for patch releases.
* [x] Tag release by running `Tag` action in Github UI against release branch, i.e. `release-X` branch.
  * Use v-prefixed version, like `v0.27.0`, for both description and tag.
* [x] Run `CI` action against release branch.
* [x] Tag the next pre-release by running `Tag` action in Github UI against `master` branch, if it's not a patch release.
  * The tag should be `v0.28.0-rc.0` if you're releasing `v0.27.x`.
* [x] Validate that you can install the published version, basic sanity check.
* [x] Run `Promote` action to promote it in `alpha` channel if it's pre-`1.0`.
* [x] Use Github UI to generate release notes.
  * Make sure to scan all PRs marked with `breaking-change` and add instructions for users to handle them.
* [x] Create the next release issue with a title that has its date, **4 weeks** after the current release day.
* [x] Announce in Slack, Twitter etc.

**Comment by haarchri** [comment]
We have one blocking issue https://github.com/crossplane/provider-aws/issues/1272

**Comment by ezgidemirel** [comment]
During the review of this [PR](https://github.com/crossplane/provider-aws/pull/1298), we identified another [bug](https://github.com/crossplane/provider-aws/pull/1298#discussion_r869473486). It would be great if we can wait for the PR.

**Comment by haarchri** [comment]
since #1298 is fixed we will start with the release 0.27

**Comment by muvaf** [comment]
@haarchri Got back from the holiday break, do you want me to assign the issue to you?

**Comment by haarchri** [comment]
I currently publish the release ;) think will be finished next 30 min

**Comment by haarchri** [comment]
basic test is done

```
NAME                                                           HEALTHY   REVISION   IMAGE                             STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/provider-aws-866abfbb37fc   True      1          crossplane/provider-aws:v0.27.0   Active                               10m27s

NAME           INSTALLED   HEALTHY   PACKAGE                           AGE
provider-aws   True        True      crossplane/provider-aws:v0.27.0   10m58s
```

**Comment by muvaf** [comment]
@haarchri Thank you!!
