### ISSUE TITLE
Elastic IP not available in v0.26.0

### ISSUE THREAD

**Issue by Rishikeshcg** [crossplane/provider-aws#1265]
### What resource do you need?
AWS Elastic IP

### What is your use case?
While creating NAT gateway, Elastic IP needs to be attached. Elastic IP Kind is missing in provider-aws@v0.26.0

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?

Yes

**Comment by haarchri** [comment]
Can you Check Address https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/Address/v1beta1@v0.26.0
