### ISSUE TITLE
Not all partitions accounted for in client when selecting SigningRegion

### ISSUE THREAD

**Issue by zonybob** [crossplane/provider-aws#1266]
### What happened?

There is some logic in the provider that handles signing region based on partition:
https://github.com/crossplane/provider-aws/blob/master/pkg/clients/aws.go#L213

It is, however, missing certain partitions - namely `aws-iso` and `aws-iso-b`. These partitions require special handling the same way that `aws-us-gov` does.

This issue is vaguely related to https://github.com/crossplane/provider-aws/pull/1020 which is what enables the ProviderConfig partition logic to even be considered.

### What environment did it happen in?
Crossplane version: 1.6.1, 
Provider 0.23.0 (with small patch taken from https://github.com/crossplane/provider-aws/pull/1020)

**Comment by haarchri** [comment]
Think we have an issue for this https://github.com/crossplane/provider-aws/issues/596
