### ISSUE TITLE
RouteTable should allow VPCPeeringConnectionIDRef like Route does

### ISSUE THREAD

**Issue by jdfalk** [crossplane/provider-aws#1267]
We're attempting to use the route table resource but noticed it doesn't have the field VPCPeeringConnectionIDRef like the route resource. Without this we will have to create all our tables manually first then apply route resources to them which defeats the purpose of automating this.

**Comment by haarchri** [comment]
why you can't use the route resource ?

**Comment by haarchri** [comment]
Yes with the latest merge from https://github.com/crossplane/provider-aws/pull/1084 it is possible with master or you need to wait for 0.27 release

**Comment by haarchri** [comment]
will be included in release 0.27 or with master branch it is possible today - thanks for opening  the request
