### ISSUE TITLE
DBCluster port number missing from the connection details secret

### ISSUE THREAD

**Issue by luisdavim** [crossplane/provider-aws#1296]
### What happened?

The connection details secret is missing the port.
Some other Crossplane providers expect the port to be in the secret, like for example, the Provider SQL.
This relates to: https://github.com/crossplane-contrib/provider-sql/issues/76

### How can we reproduce it?

Just create a DBCluster and observe the the generated connection details secret doesn't contain the port.

### What environment did it happen in?

Crossplane version: v1.7.1
Provider AWS version: v0.26.1

I've checked the code and I think it should be added to https://github.com/crossplane/provider-aws/blob/master/pkg/controller/rds/dbcluster/setup.go#L83 would a PR to add it there be acceped or is there another way of making the port available in the secret? 

I've checked https://crossplane.io/docs/v1.7/reference/composition.html#connection-details and tried to add the port using `FromConnectionSecretKey`; `FromFieldPath` and `FromValue` and couldn't find a way to get it working...

**Comment by haarchri** [comment]
@luisdavim  yes you can add this as PR - think password is also an good option
