### ISSUE TITLE
AWS networking and VPC resources to v1beta1

### ISSUE THREAD

**Issue by infinitecompute** [crossplane/provider-aws#145]
### What problem are you facing?

Would like a v1beta1 version of networking and VPC resources

### How could Crossplane help solve your problem?

Move networking and VPC resources to v1beta1 standards

### References
* https://crossplane.io/docs/v0.7/api/crossplaneio/stack-aws/network-aws-crossplane-io-v1alpha3.html

**Comment by prasek** [comment]
finished via https://github.com/crossplane/provider-aws/pull/182

**Comment by prasek** [comment]
@hasheddan just realized that [RouteTable](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/RouteTable/v1alpha4@v0.11.1) is still at `v1alpha4`, so keeping this open for now.
