### ISSUE TITLE
Add AWS DynamoDB API types and controllers 

### ISSUE THREAD

**Issue by infinitecompute** [crossplane/provider-aws#147]
### What problem are you facing?

Would like a alpha support for DynamoDB

### How could Crossplane help solve your problem?

Add CRD for API types and controller that follows best practices in https://github.com/crossplaneio/crossplane/blob/7420e6/design/one-pager-managed-resource-api-design.md.

**Comment by prasek** [comment]
@negz looks like this was wrapped up in https://github.com/crossplane/provider-aws/issues/161, so closing this out.
