### ISSUE TITLE
AWS SDK resources are not object-based as we assume

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#157]
### What problem are you facing?

In Crossplane [API Patterns doc](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#high-fidelity), high fidelity talks about exact representation of the resource in its CRD as much as possible. The assumption is that cloud provider SDK would have one struct with properties and API calls to manipulate that representation in the cloud provider. However, in cases where the main object is very lean and properties are set/get with different API calls and objects, this assumption leads to excessive amount of CRDs to be implemented, resulting in too much effort to implement them and bad UX since you have to deal with a lot of resources.

Let's take the case of IAM. In AWS console, you see 5 main objects:

<img width="273" alt="iam" src="https://user-images.githubusercontent.com/7584126/76956757-b2a3b100-6925-11ea-9598-6db7b459cc4d.png">

`Group`, `User`, `Policy`, `Role` and `Identity Provider`.

A usual workflow is that you create a `Role`, create a few `Policy` (or use ones that are built-in) then attach them to `Role`. You'd add tags to `Role` or do other operations on it in its properties tab. If you'd like to do that in Crossplane, you deal with 3 CRs `IAMRole`, `IAMRolePolicyAttachment` and `IAMPolicy`(not implemented yet). In fact, there are quite a few actions like _policy attachment_ that would deem a separate CRD but, in fact, is merely an action on the resource. Basically, the SDK is implemented in a way that you don't actually have a source of truth as object that you can modify/update for changes but a bunch of calls that you set/get those properties. It's not all of the properties, there are properties on the main struct that you can play with but in most of the cases, especially when two resources will have relation like attachment, you have other structs and calls that do the operation and our assumption about what constitutes a CRD causes us to implement a CRD for each of those actions.

When you look at other providers, such as GCP, it's closer to our assumption. You have a [ServiceAccount](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/create) endpoint and you'd construct a CRD for that, whose calls in the SDK would cover most of the cases. Though you have separate calls for resource relations here, too, like [`setIamPolicy`](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/setIamPolicy). My inclination is that this is more verbose in AWS compared to GCP; the main structs are leaner in AWS where you do most of the operations via dedicated API calls who have their own struct.

There are two problems with all this:
* We're drawn to implement too many separate resources because of how their SDK is shaped. @hasheddan was saying that we'd need 27 different resources to mirror IAM group.
* User experience suffers due to too many resources. When you look at their management consoles, they are not designed in a bottom-up fashion like we're trying to do; the consoles are decoupled and represents higher level objects together with all actions that you can do with them. 

As you can see above in the image, you don't see a resource `IAMRolePolicyAttachment` in the console's main widget; what you have is a tab in `Roles` page where you select and attach. In my opinion, this is a better user experience; as a user I don't care how you attach it or whether you need a separate call/struct for this, I would like to do it in the `Role`'s own page so that I know what I'm doing, in our case I'd like to do it under `spec` of `IAMRole` by adding a reference to the `Policy` to the existing list of attached policies.

The same problem exists in Terraform, too, in some cases. For IAM, they seem to have implemented those [relational resources](https://www.terraform.io/docs/providers/aws/r/iam_role.html). However, if you look at S3 bucket, they decided to embed all these little property structs into the main [S3 Bucket](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) resource, like [`logging`, `cors rule` etc.](https://github.com/aws/aws-sdk-go-v2/blob/master/service/s3/api_types.go#L498). It seems like they either drew a line like `if it is inter-resource relation, then a separate resoruce but if it belongs solely on one resource then it is just a property` or this is just an inconsistency due to historical reasons.

### How could Crossplane help solve your problem?

I believe we need some level of sacrifice here in terms of mirroring the API's struct and the main reason is that those structs are not meant to be interacted in a level as high as user like CRD, as we can see from how they designed their consoles. Terraform seems to have made the decision to implement inter-resource relation resources but keep the property resources on the object itself. In my opinion, we should definitely need to embed those properties to the main CRD just like they do but we can go a step further and say let's embed relational resources, too, when one side of the relation is not affected by the relation. For example, when you attach a `Policy` to a `Role`, there is no change on the `Policy`, so we can actually have `spec.attachedPoliciesRefs` under `Role` where the user can specify what `Policy`s they would like to attach to that `Role`.

I know that we don't feel good about designing the CRD in a way that is not fully mirroring the SDK but that's actually holding us back in some major way like verbose UX and excessive number of CRDs (and effort to implement each). What I propose is that we can try to mirror the UX that they provide to their end users instead of mirroring what they provide to us through their SDK. In `IAM` group, we'd have 5 different CRDs only as they show in the console and implement the separate actions as a field on the `spec` instead of implementing a new CRD for each action.

**Comment by infinitecompute** [comment]
This solution will impact the [expansion of IAM support in #151](https://github.com/crossplane/provider-aws/issues/151)

**Comment by muvaf** [comment]
We had a meeting about how to decide with @hasheddan and @negz . There are cases like S3 bucket that it makes to consolidate the structs into one CRD, like [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html) and [Terraform](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) do. As stated above, there are cases where the structs are very lean like IAM.

Instead of coming up with a tighter rule, we'll keep the sentiment expressed [here](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#high-fidelity); if there is an API then it's a candidate for being a CRD. However, we'll go for deciding on a case by case basis. For example, it makes sense to consolidate S3 structs but for IAM, it makes sense to implement another CRD for `IAMRolePolicyAttachment` because policy attachment action can be considered as an action that users might want to limit to certain people via RBAC since it means giving specific personas extra permissions.

The conclusion is that we'll go with deciding on a case by case basis with some inspirations taken from [CloudFormation](https://docs.aws.amazon.com/cloudformation/index.html) and [Terraform](https://www.terraform.io/docs/providers/aws/index.html) APIs.
