### ISSUE TITLE
AWS Certificate Manager

### ISSUE THREAD

**Issue by infinitecompute** [crossplane/provider-aws#171]
### What problem are you facing?
Would like add a support for certificate provisioning for SSL

#### User Story
* "Developer will provision a new or existing SSL certificate for their applications.  The request is for the operator to add an appropriate annotation to the Service of type LoadBalancer and/or the Ingress object to which the cert will be attached. "

### How could Crossplane help solve your problem?
Enables creation of AWS Certificate Manager resources

### References
*

**Comment by prasek** [comment]
fixed via:
 - https://github.com/crossplane/provider-aws/pull/226
 - https://github.com/crossplane/provider-aws/pull/243
