### ISSUE TITLE
Add Kinesis support

### ISSUE THREAD

**Issue by infinitecompute** [crossplane/provider-aws#174]
### What problem are you facing?
Add Kinesis support.  

### How could Crossplane help solve your problem?
Enables creation of Kinesis managed services

### References
*

**Comment by dradetsky** [comment]
My org also needs kinesis support (as well as eventbridge support) if we want to be able to adopt crossplane.

**Comment by egeland** [comment]
Looks like #857 should fill the need - wonder why it's just sitting unmerged for two months...? 🤔
