### ISSUE TITLE
Support backup and restore of all AWS managed resources

### ISSUE THREAD

**Issue by negz** [crossplane/provider-aws#181]
### What problem are you facing?

When a managed resource is backed up and subsequently restored using a tool like https://velero.io the newly restored managed resource should resume reconciliation of the external resource that was created by the backed up resource. This should be true for all AWS managed resources that support the `crossplane.io/external-name` annotation. This annotation set and/or records the actual name of an external resource, causing the newly restored managed resource to use that name.

### How could Crossplane help solve your problem?

Crossplane could ensure all AWS managed resources support the `crossplane.io/external-name` annotation. I believe the following resources need updating:

* [x] `EKSCluster` (in progress https://github.com/crossplane/provider-aws/pull/184)
* [x] `DBSubnetGroup` (in progress as part of v1beta1 work in https://github.com/crossplane/provider-aws/pull/162)
* [x] `S3Bucket` (in progress https://github.com/crossplane/provider-aws/pull/185)
* [x] `InternetGateway` (in progress https://github.com/crossplane/provider-aws/pull/191)
* [x] `RouteTable` (in progress https://github.com/crossplane/provider-aws/pull/191)
* [x] `Subnet` (in progress https://github.com/crossplane/provider-aws/pull/191)
* [x] `VPC` (in progress https://github.com/crossplane/provider-aws/pull/191)

A note on S3 bucket - despite there being a v1beta1 PR in progress, it's possible that PR will block on landing composition so I think we need to hack v1alpha3 to support external names in the meantime.

**Comment by muvaf** [comment]
It seems like all network stuff will be [v1beta1 soon](https://github.com/crossplane/provider-aws/pull/182) and they all use external name in the PR. I'll work on EKSCluster, which is the only one now that is not being worked on.

**Comment by negz** [comment]
Heads up @sahil-lakhwani, @gauravgahlot (and CC @infinitecompute) that #162 and #182 are currently the highest priority controller PRs to get wrapped up and merged, because they'll fix this related issue. Please let me know if they become at risk of not being completed by April 10th.

**Comment by infinitecompute** [comment]
@negz Is CacheSubnet Group [#186](https://github.com/crossplane/provider-aws/pull/186) intentionally excluded from this list?

**Comment by negz** [comment]
@infinitecompute It is. This is a list of existing API types that don't support backup and restore. CacheSubnetGroup doesn't exist today; it's new functionality.

**Comment by infinitecompute** [comment]
PR updates to #162 and #182 were pushed.  Please do a final review pass and merge.

**Comment by negz** [comment]
@infinitecompute @sahil-lakhwani we ended up fixing up the network resources for backup and restore in https://github.com/crossplane/provider-aws/pull/191, so #182 is no longer urgent priority.
