### ISSUE TITLE
Provide self-contained readme overview / getting started in app.yaml and readme.md

### ISSUE THREAD

**Issue by prasek** [crossplane/provider-aws#195]
### Problem
Getting started can be challenging without an overview and basic getting started steps. Having the overview and getting started docs self-contained in the repo's readme.md and the app.yaml ensures that as changes are made in a given repo, the docs can be updated in the same PR, and that published stacks can be self-documenting. Over time this getting started content can be aggregated by https://crossplane.io.

### What can we do to help?
Update the app.yaml `readme` section and readme.md overview / getting started sections with self-contained, high-level (non-CLI specific) overview and getting started steps.

For example: https://github.com/crossplane/provider-gcp follows this pattern today:
![image](https://user-images.githubusercontent.com/284840/78392940-e6294100-759d-11ea-919f-6cfe8aca86e3.png)

embedding self-contained getting started and dependency info (e.g. stack-aws-sample v0.3.0, depends on provider-aws v0.7.1) included in the the app.yaml and readme.md would also help new users:
![image](https://user-images.githubusercontent.com/284840/78393559-ebd35680-759e-11ea-9918-3207addc4d3f.png)

then later in the readme.md provide more detailed CLI-specific getting started steps, similar to https://crossplane.io/docs/v0.9/stack.html which only covers stack-minimal-gcp in v0.9

for now, link from https://crossplane.io/docs/v0.9/stack.html to each repos readme.md CLI instructions for additional stack types (e.g. AWS, Azure, Alibaba, etc.)

then in the future, we can aggregate each repos readme.md into the https://crossplane.io/docs/

**Comment by haarchri** [comment]
@luebken did you think this is still relevant ?

**Comment by haarchri** [comment]
please reopen if you think we need more stuff in readme.md in the provider
