### ISSUE TITLE
EKSCluster stuck in the Creating state, can Crossplane detect and repair this?

### ISSUE THREAD

**Issue by prasek** [crossplane/provider-aws#208]
### Problem
EKS cluster got stuck in the `Creating` state for over 2 hours:
![image](https://user-images.githubusercontent.com/284840/80764033-aa2dc100-8af4-11ea-8d12-55beeabe7369.png)

Eventually 2.5 hours later the ☝️ cluster did become `Active`.

However about 30 minutes into this, I got impatient, deleted the `KubernetesCluster` claim (the underlying managed resource didn't get deleted in this situation #209 ), and re-created the `KubernetesCluster`, which successfully provisioned a new cluster in a few minutes.

Would be nice to Crossplane detect and repair this condition (`EKSCluster` stuck in the `Creating` state) and automatically try creating a different cluster instance to improve the `AWSCluster` provisioning experience.

Using
- provider-aws v0.8.0
- stack-aws-sample v0.4.0
- crossplane 0.10.0-rc.113.ga1d1fa1
- app-wordpress v0.3.0

### Details
`EKSCluster`
```
apiVersion: compute.aws.crossplane.io/v1alpha3
kind: EKSCluster
metadata:
  annotations:
    crossplane.io/external-name: workspace1-my-cool-app-cluster-68pkv
  creationTimestamp: '2020-04-30T19:07:51Z'
  finalizers:
    - finalizer.eks.compute.aws.crossplane.io
  generateName: workspace1-my-cool-app-cluster-
  generation: 3
  name: workspace1-my-cool-app-cluster-68pkv
  resourceVersion: '697780'
  selfLink: >-
    /apis/compute.aws.crossplane.io/v1alpha3/eksclusters/workspace1-my-cool-app-cluster-68pkv
  uid: 676b33f5-058b-42f0-8c6e-c66499f16137
spec:
  claimRef:
    apiVersion: compute.crossplane.io/v1alpha1
    kind: KubernetesCluster
    name: my-cool-app-cluster
    namespace: workspace1
    uid: 54eb2512-3165-410d-9527-33b6b9966d41
  classRef:
    apiVersion: compute.aws.crossplane.io/v1alpha3
    kind: EKSClusterClass
    name: my-cool-stack-ekscluster
    uid: 139de9e5-2854-4942-af17-5cdfd8da4559
  providerRef:
    name: my-cool-stack-aws-provider
  reclaimPolicy: Delete
  region: us-west-2
  roleARN: 'arn:aws:iam::609897127049:role/my-cool-stack-iamrole'
  roleARNRef:
    name: my-cool-stack-iamrole
  securityGroupIdRefs:
    - name: my-cool-stack-eks-security-group
  securityGroupIds:
    - sg-01c12e418f7cf6745
  subnetIdRefs:
    - name: my-cool-stack-subnet-a
    - name: my-cool-stack-subnet-b
    - name: my-cool-stack-subnet-c
  subnetIds:
    - subnet-0aee82a536d6af1ba
    - subnet-0023ad2fe4e70e4f8
    - subnet-02ac89290e0405588
  vpcId: vpc-07e0865ec163c4cda
  vpcIdRef:
    name: my-cool-stack-vpc
  workerNodes:
    clusterControlPlaneSecurityGroup: sg-01c12e418f7cf6745
    clusterControlPlaneSecurityGroupRef:
      name: my-cool-stack-eks-security-group
    nodeAutoScalingGroupMaxSize: 1
    nodeAutoScalingGroupMinSize: 1
    nodeGroupName: nodegroup
    nodeInstanceType: t3.small
  writeConnectionSecretToRef:
    name: 54eb2512-3165-410d-9527-33b6b9966d41
    namespace: crossplane-system
status:
  conditions:
    - lastTransitionTime: '2020-04-30T19:07:53Z'
      reason: Successfully resolved resource references to other resources
      status: 'True'
      type: ReferencesResolved
    - lastTransitionTime: '2020-04-30T19:07:55Z'
      reason: Resource is being created
      status: 'False'
      type: Ready
    - lastTransitionTime: '2020-04-30T19:07:57Z'
      reason: Successfully reconciled resource
      status: 'True'
      type: Synced
  state: CREATING
```

**Comment by hasheddan** [comment]
It is not clear in this scenario what repairing this situation entails. One solution would be for Crossplane to delete the managed resource after a period of time, but we can not guarantee this is the behavior a user would want. I think the right solution here is to let the the resource continue to provision. A user may manually clean up in this situation if they do not want to wait.

**Comment by haarchri** [comment]
sometimes EKS Clusters needs time for provisioning - also thinks the User should cleanup If they do Not want to wait 
I will Close the issue @prasek feel free to respond if you have more points to this topic
