### ISSUE TITLE
Re-enable support for IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by hasheddan** [crossplane/provider-aws#211]
### What happened?

To conform with Crossplane's new default security context for stacks (https://github.com/crossplane/crossplane/pull/1444), the `provider-aws` container now runs as non-root (https://github.com/crossplane/provider-aws/pull/202). Because we set the non-root user in the Dockerfile, users must rebuild the container to run as root user in order to be able to read the AWS credentials that are injected from the service account into `/var/run/secrets/` in the container.

### How can we fix it?

There are a few immediate options I could see here:

1. Create a separate release for running in "insecure mode". This could use a workaround like https://github.com/kubernetes-sigs/external-dns/pull/1185#issuecomment-530439786.
2. Add fields on `ClusterStackInstall` (or the next iteration of the installation unit). This seems like the most sustainable long-term solution as there is desire to move away from including an `install.yaml` in provider packages (https://github.com/crossplane/crossplane/issues/1441).
3. Document how a user may build their own package from source in [AUTHENTICATION.md](https://github.com/crossplane/provider-aws/blob/master/AUTHENTICATION.md). This is a good short-term solution.

**Comment by hasheddan** [comment]
Some other relevant issues/PRs:
- https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8
- https://github.com/kubernetes/kubernetes/issues/82573
- https://github.com/kubernetes/enhancements/pull/1598

**Comment by muvaf** [comment]
@hasheddan Looking at https://github.com/kubernetes-sigs/external-dns/pull/1185#issuecomment-530439786 , is there any unexpected or bad side effects of using `securityContext.fsGroup: 65534` for all packages in package-manager?

**Comment by Niksko** [comment]
This is a blocker for us using Crossplane. Adding `securityContext.fsGroup: 65534` to the provider deployment seems to re-enable IRSA support. Is it possible to add this to a manifest in this repository so that it only applies to this Crossplane provider, or does it require a change in the Crossplane package manager?

**Comment by hasheddan** [comment]
@muvaf I think that would be fine. Another option would be to just set it in the `install.yaml` for AWS and then run Crossplane with `—insecure-pass-full-deployment`, which would cause Crossplane to not overwrite the security context. That being said, it would be nice if this “just worked”, so I think setting it in Crossplane should be the right solution 👍 I’ll get this fixed!
