### ISSUE TITLE
Restore RDS Instance from a backup

### ISSUE THREAD

**Issue by rberrelleza** [crossplane/provider-aws#227]
# What problem are you facing?
Every night, a new snapshot with the latest test data is generated and stored in S3. I'd like to be able to use that data when creating an RDS instance with Crossplane. 

AWS supports this natively: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceFromS3.html

**Comment by negz** [comment]
Do you have any thoughts on how this might be modelled @rberrelleza? It seems like a fairly imperative API operation. One option would be to mirror Terraform's approach and essentially make it a subobject of our spec, maybe `spec.forProvider.createFromBackup` or similar?

**Comment by rberrelleza** [comment]
That's what I was thinking @negz .  The [AWS command](https://docs.aws.amazon.com/cli/latest/reference/rds/restore-db-instance-from-s3.html) receives the location of the backup as a parameter. I think the same could be done here on a sub-object, to keep it clean, as you suggest:
```
spec:
  forProvider:
    fromBackup:
     s3: 
       bucket: mybucket
       prefix: prefix
      role: ....
```

Rhe 'recover from s3' functionality is aws-only, but cloudsql also has a similar mechanism to [create a DB from a backup](https://cloud.google.com/sql/docs/mysql/backup-recovery/backups#gcloud_1).  Not sure how much this would factor into the design, but long term it would be great to be able to support this across different cloud providers.

**Comment by jbhennin** [comment]
Curious if this has been looked at recently?  Being able to create an instance from a snapshot and point in time snapshot would be a great feature.

**Comment by juv** [comment]
Another feature that is being implicitly enabled by this is to allow developers to spin up a new database from a previous snapshot and then test new functionality on that database, then throw it away afterwards.

**Comment by matthewhembree** [comment]
Without this feature, if the database were to become corrupted, the recovery process would be:

AWS CLI, Console, Terraform, Ansible, etc. (not Crossplane):
1. Restore (point in time) a DB snapshot to a new instance.
2. pg_dump the database(s) from the new instance.
3. drop all databases in the original Crossplane instance.
4. pg_restore the database(s) to the original Crossplane instance.

This enhancement would be very helpful and provide peace of mind --skipping the intermediary instance creation.

I personally would like to see snapshots (all engines supported) as a source over S3. S3 restore is MySQL only.

**Comment by danports** [comment]
I think I've got a basic version of this (restore a MySQL backup from an S3 bucket) working...it's not going to cover all of the use cases discussed here but it could be a good start. Will open a PR soon.

**Comment by danports** [comment]
If anyone here wants to test my changes on a live cluster, feel free to install the `danports/provider-aws:rds-restore` provider. Unfortunately, this doesn't work well if you already have the official provider installed with managed resources created, since Crossplane will complain that those resources already have a controller. (Is there an easy way to change the controller for all managed resources in one shot?)
