### ISSUE TITLE
Update `IAMUserPolicyAttachment` to refer `IAMPolicy`

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane/provider-aws#231]
### What problem are you facing?

This `IAMUserPolicyAttachment` resource currently can refer to a IAM Policy in AWS by it's ARN. This issue is to update `IAMUserPolicyAttachment` so that it can refer to a IAM Policy in AWS voia an `IAMPolicy` resource in Crossplane.

### How could Crossplane help solve your problem?

There is already a resource in Crossplane called `IAMPolicy`. So, `IAMUserPolicyAttachment` can refer the `IAMPolicy` and use it's ARN (found as the value of `crossplane.io/external-name` aanotation).

**Comment by mper0003** [comment]
This feature and/or issue #177 would be great to have and really useful since we usually need to create an IAM policy suitable for each case following least privilege principle. Hopefully we can have these soon.

**Comment by sahil-lakhwani** [comment]
This has been addressed in #257 and can be closed.
