### ISSUE TITLE
Add IAMGroup as a custom resource

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane/provider-aws#233]
### What problem are you facing?

AWS IAM resources such as `IAMUser`, `IAMRole` and `IAMPolicy` are already supported by `provider-aws`. It would be nice to have `IAMGroup`. There can also be support for creating a relation between an `IAMUser`  and `IAMGroup` resources

### How could Crossplane help solve your problem?

Add a CRD and the respective controller for managing AWS IAM Group resource. Also, use the reference pattern in Crossplane to create a member relationship between `IAMGroup` and `IAMUser`

**Comment by prasek** [comment]
fixed via https://github.com/crossplane/provider-aws/pull/249
