### ISSUE TITLE
Add AWS Lambda Function as a custom resource

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane/provider-aws#234]
### What problem are you facing?

[AWS Lambda](https://aws.amazon.com/lambda/) is a managed service to run web services the 'serverless' way. It is common among AWS users to user a single or multiple Lambda Functions. 
It would be nice to have Crossplane to manage this Lambda functions

### How could Crossplane help solve your problem?

Although AWS Lambda has many features an integrations, we can start by adding support for managing a Lambda Function.

**Comment by muvaf** [comment]
Closing in favor of https://github.com/crossplane/provider-aws/issues/173
