### ISSUE TITLE
Add API Gateway as a managed resource

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane/provider-aws#235]
### What problem are you facing?

With Load balancers already in work, and Lambda proposed, API Gateway would be good for users manage REST APIs

### How could Crossplane help solve your problem?

This provider can have APIGateway as a managed resource which can provision anf manage AWS API Gateway

**Comment by muvaf** [comment]
Fixed by https://github.com/crossplane/provider-aws/pull/416
