### ISSUE TITLE
Add AWS ElasticSearch Service as managed resource

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane/provider-aws#238]
### What problem are you facing?

Elasticsearch is a powerful full text search engine, pretty commonly used for logging and analytics. 
AWS provides a managed service to provision and manage Elasticsearch. Having a managed resource that can provision an ElasticSearch would be nice.

### How could Crossplane help solve your problem?

This provider can have a managed resource to to provision and maintain AWS Elasticsearch Service.

**Comment by bcbrockway** [comment]
Considering the Elasticsearch service is no longer maintained, perhaps this should be updated to Opensearch?

**Comment by janwillies** [comment]
please see https://github.com/crossplane/provider-aws/issues/1007

**Comment by haarchri** [comment]
closed for https://github.com/crossplane/provider-aws/issues/1007

**Comment by sqerison** [comment]
Hello,
OpenSearch (old Elsasticsearch) it's another service than #1007 CloudSearch.

http://aws.amazon.com/cloudsearch/
https://aws.amazon.com/opensearch-service/

This ticket is still relevant.

**Comment by sqerison** [comment]
@haarchri could you please reopen this one?

**Comment by haarchri** [comment]
Thanks i opened again but i thinks it's better to Open a new request
