### ISSUE TITLE
Add additional unit tests for RDS client package

### ISSUE THREAD

**Issue by hasheddan** [crossplane/provider-aws#247]
### What problem are you facing?

The `pkg/clients/rds` package only has ~35% unit test coverage. This is well below the desired level.

### How could Crossplane help solve your problem?

Implement additional unit tests to achieve coverage similar to other client packages (ideally 85%+).

**Comment by enderv** [comment]
Taking a stab at this one as I have time

**Comment by hasheddan** [comment]
Thanks @enderv! Let me know if we can provide any assistance 🙂
