### ISSUE TITLE
v1beta1 EKS Cluster cannot have tags removed

### ISSUE THREAD

**Issue by hasheddan** [crossplane/provider-aws#251]
### What happened?

The v1beta1 EKS `Cluster` resource cannot have tags removed because when a diff in tags is observed, only the [TagResourceRequest](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.23.0/service/eks?tab=doc#Client.TagResourceRequest) call is made. If a tag is to be removed, we should be calling the [UntagResourceRequest](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.23.0/service/eks?tab=doc#Client.UntagResourceRequest) method.

### How can we reproduce it?

Create an EKS `Cluster` with tags. Attempt to remove a tag.

### What environment did it happen in?
Crossplane version: `v0.11.1`
provider-aws version: https://github.com/crossplane/provider-aws/commit/1d7f738aa6ead6aebe2fb6cb13155c23b5231399

**Comment by muvaf** [comment]
Fixed by https://github.com/crossplane/provider-aws/pull/288
