### ISSUE TITLE
Allow for NAT gateways to be created

### ISSUE THREAD

**Issue by cooktheryan** [crossplane/provider-aws#259]
### What problem are you facing?
Currently, no NAT gateway functionality exists to create this item within crossplane. If the functionality would be introduced we would also need to be able to modify route tables to use the created NAT gateway.

### How could Crossplane help solve your problem?
functionality would need to be created to allow for this component to be created.

**Comment by kferrone** [comment]
I did not see this was already requested. I made almost the same request here #308 .

**Comment by muvaf** [comment]
Added with https://github.com/crossplane/provider-aws/pull/342
