### ISSUE TITLE
Allow for Elastic IP creation

### ISSUE THREAD

**Issue by cooktheryan** [crossplane/provider-aws#260]
### What problem are you facing?
Elastic IP address requesting would allow for EC2 instances to use the address. Elastic IP addresses would also be a requirement for #259 

### How could Crossplane help solve your problem?
Introduce the ability to request an elastic IP address

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.23.0/service/ec2?tab=doc#Client.AllocateAddressRequest

**Comment by enderv** [comment]
I'm gonna take a stab at this as I have time.
