### ISSUE TITLE
Support for RDS Database Cluster

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#272]
### What problem are you facing?

Clustering is very common in databases. There is support for DB instances but not clusters.

### How could Crossplane help solve your problem?

Implement DB cluster managed resource using [create-db-cluster](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html) call.

**Comment by hiteshghia-splunk** [comment]
This would be awesome to have! Seems like a very common use case for anyone building a service  and wanting to use crossplane for their infra management.

**Comment by kelvinwijaya** [comment]
Hi @muvaf , would like to know if i can pickup this task?

**Comment by muvaf** [comment]
Hi @kelvinwijaya ! That'd be awesome! I don't think anyone else is working on it right now.

**Comment by kelvinwijaya** [comment]
Thanks @muvaf , i will start planning and work on this task

**Comment by anoop2811** [comment]
Hi, wanted to check if this is still in the works ?

**Comment by mdykes-gw** [comment]
Looking for the same thing... very interested

**Comment by jbhennin** [comment]
@kelvinwijaya I saw you were picking up this enhancement.  Are you still taking a look?

**Comment by kelvinwijaya** [comment]
Hey @anoop2811 , @mdykes-gw , @jbhennin , 

Sure, I will start working on this enhancement.  



Hi @muvaf ,

For this item, asking your suggestion should this be created as a separate `Kind` or still `RDSInstance` with different version?


Thanks,

**Comment by muvaf** [comment]
@kelvinwijaya I think that should be a separate kind. Possibly `apiVersion: rds.aws.crossplane.io/v1alpha1 kind: Cluster`.

**Comment by kelvinwijaya** [comment]
Hi @muvaf , 

Thanks for your suggestion. Btw how can I move this ticket to Accepted or In Progress? It seem in the the Archival now

**Comment by muvaf** [comment]
@kelvinwijaya I moved it to `In Progress` column of `v1.0` release.

**Comment by dan1** [comment]
@kelvinwijaya are there any updates on this work? Our team/company is very interested in DB Clustering support.  Thanks!

**Comment by kelvinwijaya** [comment]
Hi @dan1 ,

Apologise for the delay , I have been tied with work and have not get time to continue on the item. If you have bandwidth, kindly help to take the task up.

**Comment by hiteshghia-splunk** [comment]
I have  started working on this - https://github.com/crossplane/provider-aws/pull/489

**Comment by kelvinwijaya** [comment]
Thanks @hiteshghia-splunk for taking up the task!
