### ISSUE TITLE
v1beta1 EKS Cluster cannot change the API server endpoint access from public to private

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#276]
### What happened?
The v1beta1 EKS Cluster resource cannot change the API server endpoint access from public to private. 

### How can we reproduce it?
Create an EKS Cluster with public access. Attempt to change it to private.
```
      Endpoint Private Access:  true
      Endpoint Public Access:   false
```
Nothing happens.

### What environment did it happen in?
Crossplane version: v0.11.1
provider-aws version: 1d7f738

**Comment by muvaf** [comment]
I've looked at the code and the update request does [include](https://github.com/crossplane/provider-aws/blob/8db22ae/pkg/clients/eks/eks.go#L170) those fields. Could you share some YAMLs that I can try to reproduce?

**Comment by janwillies** [comment]
This is the yaml:
```yaml
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/external-name: irsa-test
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"eks.aws.crossplane.io/v1beta1","kind":"Cluster","metadata":{"annotations":{},"labels":{"app":"irsa-test"},"name":"irsa-test"},"spec":{"forProvider":{"resourcesVpcConfig":{"endpointPublicAccess":true,"publicAccessCidrs":["0.0.0.0/0"],"subnetIds":["subnet-abc","subnet-def"]},"roleArn":"arn:aws:iam::1234567890:role/crossplane-eks-cluster-role","version":"1.16"},"providerRef":{"name":"iat-1234567890-provider"},"writeConnectionSecretToRef":{"name":"irsa-test","namespace":"crossplane-system"}}}
  creationTimestamp: "2020-06-18T17:16:40Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 7
  labels:
    app: irsa-test
  name: irsa-test
  resourceVersion: "5560860"
  selfLink: /apis/eks.aws.crossplane.io/v1beta1/clusters/irsa-test
  uid: 3658c77e-250e-4791-bdd9-99a642266630
spec:
  forProvider:
    logging:
      clusterLogging:
      - enabled: false
        types:
        - api
        - audit
        - authenticator
        - controllerManager
        - scheduler
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: false
      publicAccessCidrs:
      - 0.0.0.0/0
      subnetIds:
      - subnet-abc
      - subnet-def
    roleArn: arn:aws:iam::1234567890:role/crossplane-eks-cluster-role
    tags:
      crossplane-kind: cluster.eks.aws.crossplane.io
      crossplane-name: irsa-test
      crossplane-provider: iat-1234567890-provider
    version: "1.16"
  providerRef:
    name: iat-1234567890-provider
  writeConnectionSecretToRef:
    name: irsa-test
    namespace: crossplane-system
status:
  atProvider:
    arn: arn:aws:eks:eu-central-1:1234567890:cluster/irsa-test
    createdAt: "2020-06-18T17:16:41Z"
    endpoint: https://F00BAR.gr7.eu-central-1.eks.amazonaws.com
    identity:
      oidc:
        issuer: https://oidc.eks.eu-central-1.amazonaws.com/id/F00BAR
    platformVersion: eks.1
    resourcesVpcConfig:
      clusterSecurityGroupId: sg-abcd
      vpcId: vpc-1234
    status: ACTIVE
  bindingPhase: Unbound
  conditions:
  - lastTransitionTime: "2020-06-18T17:28:17Z"
    reason: Resource is available for use
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-06-18T17:16:42Z"
    reason: Successfully reconciled resource
    status: "True"
    type: Synced
```

**Comment by janwillies** [comment]
Thanks for taking this on @hasheddan!

I debugged with @muvaf a bit further, it seems crossplane doesn't notice at all when I modify the `cluster` object (e.g. a cluster update from 1.16 to 1.17 also doesn't work). I'm a bit puzzled b/c I [definitely tested this](https://crossplane.slack.com/archives/CEF5N8X08/p1592432748423100?thread_ts=1591983084.401800&cid=CEF5N8X08) and it's the same installation

**Comment by hasheddan** [comment]
I am guessing this is related to https://github.com/crossplane/provider-aws/issues/251 and it is seeing a tag diff every reconcile and then trying to remove tags but is instead submitting an add tags request that is reporting successful each time without fixing the problem.

**Comment by muvaf** [comment]
@hasheddan why would it detect a tag diff every reconcile if not tag is changed?

**Comment by hasheddan** [comment]
@muvaf it could be that AWS added another tag on the resource that was not in the `spec`. Or it could be that the create request does not apply tags correctly. Either way, if a tag needed to be removed it would keep trying to Tag instead of Untag.

**Comment by muvaf** [comment]
@janwillies Would you be able to confirm that you don't experience this problem using `master` branch?

**Comment by janwillies** [comment]
yes, this works now- thanks @muvaf and @hasheddan!
