### ISSUE TITLE
Expand on Installation documentation

### ISSUE THREAD

**Issue by krishchow** [crossplane/provider-aws#290]
### What problem are you facing?

Although there is currently an INSTALL.md file in the top level of the AWS provider, there are no instructions for how to actually deploy/install the provider inside of a Kubernetes cluster. 

### How could Crossplane help solve your problem?

I think it would be beneficial to expand on this documentation for any developers working on the AWS provider.

**Comment by muvaf** [comment]
Hi @krishchow ! Are you looking for the installation to a cluster? There is a section in [`Install & Configure`](https://crossplane.io/docs/v0.12/getting-started/install-configure.html) of the main docs. If that's what you're looking for, do you mean it'd be more helpful to have those instructions in readme.md or install.md?

**Comment by krishchow** [comment]
Ah my apologies @muvaf, I can see how my original post was unclear, I specifically meant for services developers who are actively working on changes to the AWS Provider. I was not able to find much by way of documentation for running the provider.
