### ISSUE TITLE
Not possible to remove rules from securitygroup

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#300]
### What happened?

The controller supports only addition but not removal of egress/ingress rules.

AWS: 0.11.0

**Comment by marcinc** [comment]
Hi @muvaf. Would be great if the controller could support the above. Thought I'm gonna drop a line here to ask about the status there as we've just run into this exact issue in testing.

**Comment by muvaf** [comment]
@marcinc I'm planning to look at it this week.

**Comment by nabadger** [comment]
I think I'm hitting this issue too - is it related to https://github.com/crossplane/provider-aws/issues/503 ?
