### ISSUE TITLE
Redshift CRD cannot properly created by ClusterPackageInstall

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#312]
Due to the CRD (clusters.redshift.aws.crossplane.io) with openAPIV3Schema validation https://github.com/crossplane/provider-aws/blob/v0.11.0/config/crd/redshift.aws.crossplane.io_clusters.yaml

![image](https://user-images.githubusercontent.com/11241076/89284245-0c143e80-d681-11ea-92aa-31251ea4c967.png)

## What happened?
Error in ClusterPackageInstall, Type is wrong for maximum and minimum field (see the attached image above)
```
spec:
  package: crossplane/provider-aws:master
status:
  conditionedStatus:
    conditions:
    - lastTransitionTime: "2020-08-04T08:58:22Z"
      reason: Resource is being created
      status: "False"
      type: Ready
    - lastTransitionTime: "2020-08-04T08:58:34Z"
      message: 'can not update existing CRD clusters.redshift.aws.crossplane.io from
        job provider-aws: failed to convert unstructured crd from job log: cannot
        convert int64 to float64'
      reason: Encountered an error during resource reconciliation
      status: "False"
      type: Synced
  installJob:
    apiVersion: batch/v1
    kind: Job
    name: provider-aws
    namespace: crossplane-system
    uid: 882b90cf-fb35-4319-b0f5-508be6d100bd
```

Based on the Spec highlighted below:

![image](https://user-images.githubusercontent.com/11241076/89285077-50eca500-d682-11ea-9a43-12b58aa4708f.png)

![image](https://user-images.githubusercontent.com/11241076/89285621-48489e80-d683-11ea-9d09-95cf19818a18.png)

Which relate to the JSONSchemaProps object, this is declared as float64* type, so in the main CRD , it should use the same type as well (not int64)

![image](https://user-images.githubusercontent.com/11241076/89285120-64980b80-d682-11ea-945b-81617cb2b038.png)
 

### How can we reproduce it?
Install with the latest provider (master branch)

When i revert to this specific release `package: "crossplane/provider-aws:v0.11.0-rc.134.gae43e9b"`, it works

### What environment did it happen in?
Crossplane version: v0.11.1 (master)

* Cloud provider or hardware configuration : AWS
* Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeS
tate:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419e
b", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) : EKS
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
-->

**Comment by hasheddan** [comment]
@kelvinwijaya was the RDS CRD already present when you created the `ClusterPackageInstall`?

**Comment by kelvinwijaya** [comment]
Hi @hasheddan , yes the existing RDS CRD is there already, anyway this issue happen only for Redshift CRD . the RDS one is updated successfully, this issue happen after i pull the latest version of ClusterPackageInstall as i have always been pointing to master branch, understand the Redshift CRD addition is quite recent based on you branch commit date

**Comment by kelvinwijaya** [comment]
Hi @hasheddan ,

Have installed with the latest `crossplane/provider-aws:master` repo _commitid_: 19f472d223e97934c64aec511c6d237e43532300, issues on refshift cluster crd creation seem has gone. 

Thanks,
Kelvin

**Comment by muvaf** [comment]
> issues on refshift cluster crd creation seem has gone.

Closing the issue as it seems to be fixed.
