### ISSUE TITLE
ReplicationGroup should have referencer support for cacheSubnetGroup

### ISSUE THREAD

**Issue by krishchow** [crossplane/provider-aws#313]
### What problem are you facing?
Hi, I am attempting to use the ReplicationGroup to create a Redis cluster on AWS. I am creating a composition to create all the necessary VPC subnets/security group. However, for the cache subnet group, although I create a CacheSubnetGroup, the name is generated, and I cannot reference this inside of my ReplicationGroup CR.

### How could Crossplane help solve your problem?
I noticed there was a cacheSubnetGroupName field in the CR for the ReplicationGroup, however, this only accepts strings. It would be very useful if I could use a selector to access the cache subnet group I created using Crossplane.

**Comment by hasheddan** [comment]
@krishchow good catch! The `CacheSubnetGroup` resource is pretty new. Would you want to add the referencers in the `ReplicationGroup` to it?
