### ISSUE TITLE
Provider unable to deploy in Openshift

### ISSUE THREAD

**Issue by krishchow** [crossplane/provider-aws#316]
### What happened?

When attempting to deploy the AWS provider into an Openshift cluster, the deployment will be created, but it will fail to create the pod for the controller. It cites an error in the fsGroup for the security context.

### How can we reproduce it?

Install a fresh version of master for the AWS provider onto Crossplane, see the logs for the pod before it crashes

### What environment did it happen in?
Crossplane version: crossplane-alpha

Using the current master branch of the AWS Provider - be12f54
OpenShift version - 4.4.10

### Potential Fix

The known hotfix involves going into the YAML for the deployment and removing the offending line (typically line 62) with the value "fsGroup: 65534", it seems like Openshift will then generate the appropriate value for this field behind the scenes.
I believe the offending line is inside the package/.registry/install.yaml file for the provider-aws.

**Comment by hasheddan** [comment]
@krishchow thanks for opening this! This was added to enable the IAM roles for EKS clusters as described in https://github.com/crossplane/provider-aws/issues/211. When investigating this I remember reading that Openshift assigns a pseudo-random fsGroup. This is likely something that we should make configurable to providers at install time, but we do not currently have a mechanism to do so. I will keep this open to track that work :+1:

**Comment by muvaf** [comment]
@hasheddan with the new package manager, is this issue solved?

**Comment by hasheddan** [comment]
@muvaf yep! Good catch 👍
