### ISSUE TITLE
Import existing aws IAM policy fails

### ISSUE THREAD

**Issue by mper0003** [crossplane/provider-aws#323]
### What happened?

I'm creating `IAMPolicies` using crossplane. I already have some IAM policies in my aws account that I would like to import into my cluster as a crossplane managed resource. I tried using the `crossplane.io/external-name` annotation as specified in the documentation [here](https://crossplane.io/docs/v0.11/introduction/managed-resources.html#importing-existing-resources). However, I still get an error saying a resource with the same name already exists.
```
Warning  CannotCreateExternalResource  111s (x446 over 168m)  managed/iampolicy.identity.aws.crossplane.io  (combined from similar events): failed to create the IAM Policy: EntityAlreadyExists: A policy called mp-managed-policy already exists. Duplicate names are not allowed.
           status code: 409, request id: a6a0e542-10ff-4ebb-8d58-145238306e4
```

### How can we reproduce it?

- Create an IAM policy in your aws account
- Define an IAMPolicy custom resource and add the `crossplane.io/external-name` annotation with the name of the policy created in the previous step.
```
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: mp-managed-policy
  annotation:
    crossplane.io/external-name: mp-managed-policy
spec:
  forProvider:
    name: mp-managed-policy
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "elastic-inference:Connect",
              "Resource": "*"
          }
        ]
      }
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider

```

- Apply the IAMPolicy resource into the cluster

### What environment did it happen in?
Crossplane version: v0.12.0
provider-aws version: v0.11.0

**Comment by muvaf** [comment]
Hi @mper0003 ! Could you copy the exact format of the `crossplane.io/external-name` you provided? From my reading of [the code](https://github.com/crossplane/provider-aws/blob/master/pkg/controller/identity/iampolicy/controller.go#L123), it expects full ARN of the policy.

**Comment by mper0003** [comment]
Hi @muvaf , I only provided the name of the policy in the `crossplane.io/external-name`, following [this](https://crossplane.io/docs/v0.11/introduction/managed-resources.html#importing-existing-resources) documentation.
Using the existing policy full ARN works, so I'm closing this issue. Thank you!

**Comment by muvaf** [comment]
Yeah, it's usually easy to guess what format `crossplane.io/external-name` expects but in some cases like this one, it could be hard and I'm not aware of a place we have this documented. @hasheddan can we add comment for special annotations like this one in docs.crds.dev?
