### ISSUE TITLE
Support for Launch Templates

### ISSUE THREAD

**Issue by enderv** [crossplane/provider-aws#338]
### What problem are you facing?
Currently no support for launch template. If added these can be used for either autoscaling groups or EKS node groups.

### How could Crossplane help solve your problem?
Implement a managed resource for launch templates

**Comment by duncaan** [comment]
Would like to see this too, for use with EKS node groups, specifically.

**Comment by muvaf** [comment]
@duncaan Would you be interested in completing the custom parts outlined [here](https://github.com/crossplane/provider-aws/pull/486) if we're able to generate this resource?

**Comment by stecky** [comment]
I would also like to see this. Currently I need to tag the ec2 instances that get created as part of my node groups, but the only way to do that is to use a launch template

**Comment by stecky** [comment]
It looks like this isn't even going to be possible until PR #602 get's merged

**Comment by haarchri** [comment]
aws shipped https://aws.amazon.com/de/about-aws/whats-new/2021/10/amazon-eks-nodes-groups-bottlerocket/ for user-data optionally support fields (https://github.com/bottlerocket-os/bottlerocket#kubernetes-settings) for bottlerocket we need launch-templates 

https://github.com/crossplane/provider-aws/pull/898

**Comment by tanujd11** [comment]
Is this by any chance picked by someone for next release? Will be happy to collaborate if not.

**Comment by haarchri** [comment]
@tanujd11 i can review if you open the PR ;)
