### ISSUE TITLE
Notification group should be renamed to SNS

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#340]
### What happened?

`notification.aws.crossplane.io` should be `sns.aws.crossplane.io` because its managed resources (SNSTopic, SNSSubscription) belongs to [`sns`](https://github.com/aws/aws-sdk-go-v2/tree/master/service/sns) group in the AWS SDK. Also, the resource kinds should be renamed to `Topic` and `Subscription` after that change.

**Comment by haarchri** [comment]
@muvaf something for v0.23.0 ?

**Comment by muvaf** [comment]
Closing in favor of https://github.com/crossplane/provider-aws/issues/1109
