### ISSUE TITLE
S3 to support Bucket Encryption

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#341]
### What problem are you facing?
To protect Data at rest in S3 Bucket. Need to have S3 feature support to enable attaching the AWS KMS keys

### How could Crossplane help solve your problem?
Enhance the data security of the S3 bucket provisioned through Crossplane

**Comment by muvaf** [comment]
https://github.com/crossplane/provider-aws/pull/331 should fix this issue.
