### ISSUE TITLE
Implement KMS Key managed resource

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#357]
### What problem are you facing?

AWS Provider does not have support for KMS Key resource.

### How could Crossplane help solve your problem?

Implement `kind: Key, apiVersion:kms.aws.crossplane.io`managed resource.

**Comment by marcinc** [comment]
Hello @muvaf. Appreciate it may be of low priority for most but curious whether we should expect KMS Key support any time soon?

**Comment by janwillies** [comment]
I believe @henni was able to spend some time and will share soon

**Comment by Henni** [comment]
PR incoming next week

**Comment by Savasw** [comment]
@Henni Any update on this?
