### ISSUE TITLE
Support for AWS TransitGateway and TransitGatewayAttachment

### ISSUE THREAD

**Issue by HerrmannHinz** [crossplane/provider-aws#363]
### What problem are you facing?

in my team we spin up clusters per default with internal load balancers + we have multiple clusters in different AWS accounts.
to make them available to the corp intranet + to VPN users etc. we are doing some transit gateway peering afterwards to make a cluster: 

- availability  to the internal network/routing 
- ensure visibility  to other parts of the infrastructure(CI/CID) in different AWS accounts 
- enable the new cluster to also reach other pieces of infra. like CI/CD, services in other clusters or RDS instances 
- also: we create a 2nd VPC in the same account which contains only RDS instances for better separation of concerns(well, that may not matter)

currently we need to run dedicated pipeline tasks after the cluster creation to apply _terraform code_ which is doing the necessary TGW peering.  
we are currently using SAP gardener as our cluster lifecycle management tool. gardener provides CRD's to CRUD the clusters. 

_argoCD_ is our tool to apply those manifests against a management(seed) cluster.
_argoCD_ is also our tool of choice for applying additional landscape deployments like prometheus-operator, nginx etc. 
now if we want to do the TGW peering we need to go one step back and involve some tooling(tekton pipelines) to apply the terraform code against the AWS account. 

### How could Crossplane help solve your problem?

would be super cool to also deploy those infrastructure changes/resources via _argoCD_ and kubernetes manifests. 

see: https://crossplane.slack.com/archives/C01718T2476/p1601571788009400
and: https://kubernetes.slack.com/archives/CD6U2V71N/p1601564676059800

i think you get the idea. :) 

thanks in ahead for considering this feature request.

**Comment by muvaf** [comment]
@HerrmannHinz Thank you for describing your request in detail! 0.13 will be released this week, so I believe we can discuss this feature for 0.14. Though if you'd like to, you can contribute by implementing them by following our guides. We'd be more than happy to help you guide along and merge the PR to upstream.

* Provider Development Guide: https://crossplane.io/docs/master/contributing/provider_development_guide.html
* Implementing a managed resource (GCP PubSub) live: https://www.youtube.com/watch?v=rvQ8N0u3rkE&t=7s

**Comment by HerrmannHinz** [comment]
@muvaf wow nice, good news and thanks for the heads up. 
will check out the docs and the tutorial. maybe i can manage it myself to implement it. but please do not wait for me. ;)

**Comment by haarchri** [comment]
@HerrmannHinz please look at #831 tgw & tgw-vpc-attachment currently working in my PR - one open point with code-gen but in general it is working ;)
