### ISSUE TITLE
Update AWS SDK v2 version

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#383]
### What problem are you facing?

I've been getting `The XML you provided was not well-formed or did not validate against our published schema` in some S3 calls and I suspect it might be related to the AWS SDK version (`github.com/aws/aws-sdk-go-v2 v0.23.0`) we are using.

### How could Crossplane help solve your problem?

Update to [v0.26.0](https://github.com/aws/aws-sdk-go-v2/releases/tag/v0.26.0) which has some significant changes from what I can tell.

**Comment by enderv** [comment]
Started working on bumping to their rc .0.31.0 as I have time. It is indeed a major change.

**Comment by muvaf** [comment]
@enderv FWIW, we use AWS SDK v1 as well, which is GA as opposed to v2. So, if you don't want to deal with updating SDK, you can opt for using v1 in the controller you want to make a change.

**Comment by negz** [comment]
We're continuing to use SDK v1 because ACK uses SDK v1 - we will revisit this later once there's ACK support for v2.

**Comment by enderv** [comment]
Question on this: all of the current non ack resources use v2 already.  Just gonna stick on the old v2 version until they go to ack generated resources?

**Comment by muvaf** [comment]
@enderv I think we're indifferent about what SDK they use but unless necessary, I wouldn't spend much effort updating them to newer v2 versions. In fact, we can think about downgrading them to v1 if the feature that's available in newer v2 versions is available there.

**Comment by muvaf** [comment]
v2 SDK has gone GA and the current released version is [v1.3.0](https://github.com/aws/aws-sdk-go-v2/releases/tag/v1.3.0) which I think we should upgrade to as soon as we can.

**Comment by enderv** [comment]
Have done a lot of work on this in my [aws-update branch](https://github.com/enderv/provider-aws/tree/aws-update) to get to 1.1. Just keep getting distracted with other things and new resources keep coming in. Did another rebase this morning and a few tests are failing but just wanted to call it out here in case someone else had more time and didn't want to start from scratch.

**Comment by muvaf** [comment]
Fixed with https://github.com/crossplane/provider-aws/pull/602 and https://github.com/crossplane/provider-aws/pull/855
