### ISSUE TITLE
Implement EKS Fargate Profile

### ISSUE THREAD

**Issue by Knappek** [crossplane/provider-aws#407]
### What problem are you facing?

I would like to be able to schedule pods on Fargate: https://docs.aws.amazon.com/eks/latest/userguide/fargate.html.

### How could Crossplane help solve your problem?

Implement `kind: FargateProfile, apiVersion: eks.aws.crossplane.io`

**Comment by Knappek** [comment]
I am working on this...

**Comment by muvaf** [comment]
Thanks @Knappek ! Here is some resources that might help:
* Provider Development Guide - https://crossplane.io/docs/master/contributing/provider_development_guide.html
* Live coding of GCP PubSub managed resource - https://www.youtube.com/watch?v=rvQ8N0u3rkE&t=7s
