### ISSUE TITLE
Incorrect SecurityGroup Resource cidrIp API Documentation

### ISSUE THREAD

**Issue by phantasm66** [crossplane/provider-aws#422]
According to the API docs for `SecurityGroup` Crossplane resources, we should be able to specify an existing source SG in `spec.forProvider.ingress.ipRanges.cidrIp`: https://github.com/crossplane/provider-aws/blob/c603ea315856c7cfb70594308bc8d3f940160640/package/crds/ec2.aws.crossplane.io_securitygroups.yaml#L82-L84

However, this does not seem to be the case:
```
Events:
  Type     Reason                        Age   From                                         Message
  ----     ------                        ----  ----                                         -------
  Normal   CreatedExternalResource       12m   managed/securitygroup.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Warning  CannotUpdateExternalResource  12m   managed/securitygroup.ec2.aws.crossplane.io  failed to authorize ingress rules: InvalidParameterValue: CIDR block sg-05cbbd25a44de07f5 is malformed
           status code: 400, request id: 439e5ee2-661f-4138-9bad-9747e37f9c8d
```
This API documentation exists for both `ingress` ipv4 and ipv6 specs, as well as `egress` ipv4 and ipv6 specs.

It would be fantastic if we could actually specify an existing source SG in `spec.forProvider.ingress.ipRanges.cidrIp`. I'm not sure what would be involved to support that though, so for now, I suppose I'm requesting an update the API docs to remove the implication that this feature _is supported_.

### What environment did it happen in?
Crossplane version: `v0.13`

* Cloud provider or hardware configuration: `AWS us-east-1 region`
* Kubernetes version (use `kubectl version`): `v1.17.12`
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): `Kubernetes` (not from a provider distro)
* OS (e.g. from /etc/os-release): `Ubuntu 16.04.7 LTS (Xenial Xerus)`
* Kernel (e.g. `uname -a`): `4.4.0-1113-aws #126-Ubuntu SMP Fri Aug 14 13:24:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by muvaf** [comment]
The documentation is copied directly from AWS.
> You can either specify a CIDR range or a source security group, not both.

I believe what is meant here is that you can either use this field to give a CIDR range or a source security group (via another field) but you cannot fill both of the fields. From what I can tell, that other field is `spec.forProvider.ingress.userIdGroupPairs.groupId`

**Comment by muvaf** [comment]
@phantasm66 feel free to reopen if your question isn't answered.
