### ISSUE TITLE
Add @krishchow as a provider-aws maintainer

### ISSUE THREAD

**Issue by hasheddan** [crossplane/provider-aws#438]
@krishchow has been contributing significant features to `provider-aws` over the past few months. He has also been responsive and reactive to opened issues and big fixes. I believe he has demonstrated all qualities we expect in a [Crossplane maintainer](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#becoming-a-maintainer).

This issue proposes adding @krishchow as a `provider-aws` maintainer. Existing maintainers should indicate votes in the comments.

/cc @negz @muvaf

**Comment by hasheddan** [comment]
Needless to say, this is a +1 from me :tada:

**Comment by muvaf** [comment]
Congrats @krishchow ! +1 from me!

**Comment by negz** [comment]
+1 from me! Thanks for all the great work you've been doing @krishchow - we appreciate it.
