### ISSUE TITLE
Correct order of steps when using service accounts with IAM role

### ISSUE THREAD

**Issue by bandesz** [crossplane/provider-aws#472]
### What happened?

I've created an IAM role, annotated the service account, set an fsgroup and created the required provider config on the security context on the provider's deployment. I'm not sure what happens but I get the following error on resources I try to create:

```
'connect failed: unable to read web identity token file in pod: open
      : no such file or directory'
```

After restarting the pod authentication starts to work.

What is the correct order of the following steps?
 - creating the provider config
 - annotating the service account
 - setting the fsgroup on the deployment

I'm installing the provider using the Helm chart's provider.packages option.

Crossplane: 1.0.0
AWS provider: 0.16.0

**Comment by muvaf** [comment]
@hasheddan is this still happening with your recent updates?

**Comment by hasheddan** [comment]
I think the [updated doc](https://github.com/crossplane/provider-aws/blob/master/AUTHENTICATION.md) should work here. @bandesz could you confirm?

**Comment by bandesz** [comment]
@hasheddan I just changed our setup to use ControllerConfig today (based on the linked docs), and all seem to work, so I will close this. Good timing with your question :)
