### ISSUE TITLE
s3.aws.crossplane.io/v1beta1 instance does not change the "Ready" state to "True" when specifying "spec.forProvider.notificationConfiguration"

### ISSUE THREAD

**Issue by lvalerio** [crossplane/provider-aws#476]
### What happened?

When I apply the configuration for an S3 bucket with notifications sent to an SQS queue I expect the command `kubectl get managed` to show the bucket.s3.aws.crossplane.io as READY = True. However, it never changes from READY = False. When I look in the AWS console, I see the bucket is created and the notifications are configured. The only issue I see in the console is the SQS queue that is the target of the notifications keeps receiving "s3:TestEvent". Not sure if that is expected behavior, related to the issue or a separate issue altogether.

### How can we reproduce it?

1. Create an SQS queue.
2. Create an S3 bucket using the configuration below:
```bash
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: test-bucket.helloworld.net
  namespace: test-namespace
spec:
  forProvider:
    locationConstraint: us-east-1
    acl: public-read
    notificationConfiguration:
      queueConfigurations:
        - queueArn: arn:aws:sqs:us-east-1:YOUR-AWS-ACCOUNT:test-queue
          events:
            - s3:ObjectCreated:*
            - s3:ObjectRemoved:*
            - s3:ObjectRestore:Completed
          filter:
            key:
              filterRules:
                - name: suffix
                  value: .py
  providerConfigRef:
    name: default
```
3. Run the command `kubectl get managed`

### What environment did it happen in?
Crossplane version: v0.14.0

Kubernetes version: 
```bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Kubernetes distribution: kind version 0.9.0

OS: 
```bash
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```
Kernel: Linux cli-vm 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by iAnomaly** [comment]
I can't speak to the notification/SQS piece, but I'm experiencing this same issue with Bucket READY = False on Crossplane version `v0.13.0`.

Using the above as an example, neither `kubectl get managed` or `kubectl get Bucket` are showing READY = True for the resource even though I can confirm its creation/existence in AWS just as @lvalerio has experienced.

**Comment by muvaf** [comment]
I'll test this and let you know.

**Comment by haarchri** [comment]
fixed with: https://github.com/crossplane/provider-aws/pull/917
