### ISSUE TITLE
IsUpToDate Error Propagation

### ISSUE THREAD

**Issue by Henni** [crossplane/provider-aws#501]
### What problem are you facing?
I want to execute AWS SDK calls in the `IsUpToDate` function of a resource controller (i.e. KMS Key).
At the moment there is no way to propagate any errors that arise during these calls up to the reconciler, because `IsUpToDate` has no error return type.

### How could Crossplane help solve your problem?
Modify the auto-generation template to include an error return type for `IsUpToDate`.

**Comment by muvaf** [comment]
Fixed by https://github.com/aws/aws-controllers-k8s/pull/654
