### ISSUE TITLE
Add AWS code generator to Make targets

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#526]
### What problem are you facing?

To generate a resource, we need to clone the code-generator [manually](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md).

### How could Crossplane help solve your problem?

We can add a target to Makefile to do it in provider-aws repo like `make service rds`

**Comment by nitinrajput1997** [comment]
I want to contribute this as my good first issue. Can I start working on it ?

**Comment by muvaf** [comment]
@nitinrajput1997 Yes, that'd be great!! Let me know if you need any help.

**Comment by nitinrajput1997** [comment]
@muvaf please assign this issue to me .I want to contribute it as my good first issue .
