### ISSUE TITLE
ReplicationGroup: Add support for shards (node groups) scaling

### ISSUE THREAD

**Issue by petteja** [crossplane/provider-aws#531]
### What problem are you facing?
It is impossible to change the number of node groups for a ReplicationGroup after deployment. Redis (cluster mode enabled) replication group does allow this, but Crossplane does not.

Probably related to https://github.com/crossplane/provider-aws/blob/master/pkg/clients/elasticache/elasticache.go#L193-L212 and https://github.com/crossplane/provider-aws/blob/f600ff88ad64df73295c96e4446be83b608ddfa4/apis/cache/v1beta1/replication_group_types.go#L424 (immutable)

### How could Crossplane help solve your problem?
This is probably a common use case which Crossplane should be able to handle.

**Comment by eloo** [comment]
Are there any update on this topic? 
Its really weird that we can not scale the replicationGroup.

**Comment by gammpamm** [comment]
I would need that too
