### ISSUE TITLE
Configure Service Account Name

### ISSUE THREAD

**Issue by nonamef** [crossplane/provider-aws#534]
### What problem are you facing?
I am unable to automate setting up OIDC authentication due to the manual step 4  to copy the SERVICE_ACCOUNT_NAME in https://github.com/crossplane/provider-aws/blob/master/AUTHENTICATION.md. 

### How could Crossplane help solve your problem?
If the SERVICE_ACCOUNT_NAME could be configured, then setting up the IAM Role trust relationship could be automated.

**Comment by mentos1386** [comment]
Having the same issue. I'm trying to provision Crossplane using Terraform. I can do everything but the OIDC, as service account name is not deterministic.

**Comment by muvaf** [comment]
Since we're using `provider-aws-*` in the IAM policy, I think `SERVICE_ACCOUNT_NAME` is not effective anymore. Maybe a PR to remove it is due. cc @hasheddan

**Comment by mentos1386** [comment]
@muvaf Ooh, my bad. I was using `StringEquals` with `provider-aws-*` when i must use `StringLike` for IAM definition. This isn't actually a problem for me then :)

**Comment by nonamef** [comment]
Thanks that would solve the problem.
