### ISSUE TITLE
Assigning ECR repository permission

### ISSUE THREAD

**Issue by hassbert** [crossplane/provider-aws#535]
### What problem are you facing?
The current [ecr repository object](https://doc.crds.dev/github.com/crossplane/provider-aws/ecr.aws.crossplane.io/Repository/v1alpha1@v0.16.0) is not able to assign permission on the ecr repo. In cross account environments this is needed because setting permissions on the repository is the easiest way to share repositories. This enables especially cross account CICD setups.

### How could Crossplane help solve your problem?
Setting these permissions could be implemented either within the existing repository object or (similar to [bucketPolicy](https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/BucketPolicy/v1alpha2@v0.16.0) for S3) as addtional object.

See here the terraform [ecr_repository_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository_policy) resource for example.
The [aws sdk](https://github.com/aws/aws-sdk-go/blob/v1.37.7/models/apis/ecr/2015-09-21/docs-2.json#L31) supports that as well.

**Comment by HerrmannHinz** [comment]
i think the request is similar to this one: 

https://github.com/crossplane/provider-aws/pull/506
