### ISSUE TITLE
Implement Amazon Cloud Map service

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#562]
### What problem are you facing?
Amazon Cloud Map resources are missing.

https://docs.aws.amazon.com/sdk-for-go/api/service/servicediscovery/

### How could Crossplane help solve your problem?
Use ACK to generate servicediscovery and then fill the gaps.

**Comment by haarchri** [comment]
implemented with https://github.com/crossplane/provider-aws/pull/627
