### ISSUE TITLE
Resource for RDS PostgreSQL DB Parameter Groups

### ISSUE THREAD

**Issue by Dkaykay** [crossplane/provider-aws#567]
Hi, 
besides the RDSInstance CRD, it should be possible to create / update / delete RDS Parametergroups with crossplane:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html

### What problem are you facing?
Currently it is only possible to provide the name of an existing parameter group to RDSInstance. I need to create a new parameter group with crossplane. 

### How could Crossplane help solve your problem?
Implement a CRD for db parameter groups

**Comment by jbhennin** [comment]
No only should you be able to create parameter groups, the ability to update parameter group parameters is also needed.
This should exist for both RDS Clusters and Instances and

**Comment by muvaf** [comment]
Hi @Dkaykay ! Thanks for opening the issue! It seems like our [code generation pipeline](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md) supports generating this resource. Would you be interested in contributing?

**Comment by Dkaykay** [comment]
Implemented basic functionalities for creating, updating and deleting RDS DB Parametergroups and created above PR

**Comment by chlunde** [comment]
I think this is solved? Closing.
