### ISSUE TITLE
Secondary VPC CIDR support

### ISSUE THREAD

**Issue by enderv** [crossplane/provider-aws#581]
### What problem are you facing?
To take advantage of [CNI custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) on EKS need the ability to add secondary CIDR's to the vpc

### How could Crossplane help solve your problem?
Add support for adding secondary CIDR's to a VPC

**Comment by muvaf** [comment]
Do you know what API call needs to be made to do that?

**Comment by enderv** [comment]
@muvaf - Looks like [AssociateVpcCidrBlockRequest](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.23.0/service/ec2#AssociateVpcCidrBlockRequest) I can take a stab at adding it just wasn't sure if we should add another field onto VPC with secondary CIDR's or make this its own resource  and just reference a VPC

**Comment by muvaf** [comment]
I think it should be a separate resource named `VPCCIDRBlock`. Seems like Terraform also treats it separately https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipv4_cidr_block_association
