### ISSUE TITLE
No support for resource tags in IAMPolicy

### ISSUE THREAD

**Issue by mf-lit** [crossplane/provider-aws#599]
### What happened?

I've noticed that the IAMPolicy MR has no support for tags (unlike say, IAMRole). I couldn't see an existing issue or PR for this so thought I'd note it quickly.

### What environment did it happen in?
Crossplane version: 1.1
Provider: 0.17

**Comment by ra-grover** [comment]
@mf-lit I opened a PR to add this feature.
#910
