### ISSUE TITLE
Resource Access Manager (RAM) support

### ISSUE THREAD

**Issue by enderv** [crossplane/provider-aws#603]
### What problem are you facing?
Looking to use Transit Gateways to solve some networking issues but you need to share Transit Gateways to be able to use them cross account.

Currently transit gateways aren't supported either but open issue for them: https://github.com/crossplane/provider-aws/issues/363

### How could Crossplane help solve your problem?
Provide support for RAM resources and accepting similar to the terraform resources

- [aws_ram_resource_share](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_share)
- [aws_ram_principal_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_principal_association)
- [aws_ram_resource_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_association)
- [aws_ram_resource_share_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_share_accepter)

**Comment by RafalMaleska** [comment]
would need RAM to share certificateauthorities over aws multiple aws accounts
