### ISSUE TITLE
Implement IOT resources

### ISSUE THREAD

**Issue by mentos1386** [crossplane/provider-aws#609]
### What problem are you facing?

AWS IOT resources are missing.

https://docs.aws.amazon.com/sdk-for-go/api/service/iot/

### How could Crossplane help solve your problem?

Use Crossplane to create:
 * Thing Groups
 * Types
 * Billing Groups
 * Jobs
 * Provisioning Template
 * ...Others?

There seems to be a bunch of resources tied to IOT space. Some might not be as important as their use case with Crossplane is limited, Things for example. But some as Types and Thing Groups would be nice, as they are something we would like our application to use, and not "worry" about.

**Comment by muvaf** [comment]
Would you be willing to contribute these resources using our [Code Generation Guide](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?

**Comment by mentos1386** [comment]
@muvaf I'll check it out :)

**Comment by haarchri** [comment]
Thing & Policy is merged with #940

**Comment by haarchri** [comment]
i would prefer that folks can Open a followup issue when more iot resources needed - to see the real need in the community
