### ISSUE TITLE
add oidc identity provider to eks

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#610]
### What problem are you facing?
Currently the only way to login to an eks cluster which was provisioned by `provider-aws` is via IAM user.
Recently AWS added the [feature](https://aws.amazon.com/de/blogs/containers/introducing-oidc-identity-provider-authentication-amazon-eks/) to login to an eks cluster via oidc, but it's not yet supported by `provider-aws`

### How could Crossplane help solve your problem?
The eks resource in `provider-aws` should be updated with the `oidc` configuration options: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks@v1.2.0/types#OidcIdentityProviderConfigRequest

Depends on https://github.com/crossplane/provider-aws/issues/383

**Comment by janwillies** [comment]
Yeah that makes sense. I believe you can generate the resource with codegen, as @MisterMX did it in #863

**Comment by haarchri** [comment]
for CodeGenerator we need first https://github.com/crossplane/provider-aws/pull/801 because  OIDC identity Provider calls are available since 1.37.10 ... .. 
https://github.com/aws-controllers-k8s/community/issues/883
