### ISSUE TITLE
AWS SecretsManager implementation does not sync existing secrets to Kubernetes

### ISSUE THREAD

**Issue by juv** [crossplane/provider-aws#641]
### What happened?

Crossplane's AWS SecretsManager implementation for `Secret` is a unidirectional implementation only. When trying to sync existing secrets from AWS SecretsManager to a Kubernetes Secret by using the [external-name](https://crossplane.io/docs/v1.1/concepts/managed-resources.html#importing-existing-resources) annotation, the expected Kubernetes secret is not being created. The other way around, creating an AWS SecretsManager secret from Crossplane works as expected. 

### How can we reproduce it?

1. Create a AWS SecretsManager secret
2. Try to reference that existing Secret with Crossplane's `external-name` annotation in your [Secret spec](https://doc.crds.dev/github.com/crossplane/provider-aws/secretsmanager.aws.crossplane.io/Secret/v1alpha1@v0.17.0)
3. The secret in Kubernetes will not be created

### What environment did it happen in?
Crossplane version: v1.1

AWS
EKS 1.19
Crossplane provider-aws 0.17.0

**Comment by MisterMX** [comment]
The issue you are describing could be solved by implementing `LateInitialize` in the secretsmanager.

However, if you are also referring to a *constant* bi-directional sync between AWS and K8s, I am not sure if this is possible. Because K8s secrets do - as far as I know - not expose something like a `lastChangedTimeStamp` it is not possible for the controller to decide which secret value is newer and therefore the desired one.

@muvaf  what do you think?

**Comment by juv** [comment]
I was not thinking about a bi-directional sync. My usecase is to have a SecretsManager secret with [automatic rotation](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets-other.html) and sync that to Kubernetes

**Comment by MisterMX** [comment]
OK, now I understand what you mean. Yes, secret rotation is currently not supported by Crossplane but could be implemented.

As a workaround for now, you could use [external-secrets-controller](https://github.com/external-secrets/kubernetes-external-secrets) to sync secrets from AWS to K8s.

**Comment by juv** [comment]
I agree that auto rotation for secrets generated by Crossplane would be nice to have as well, but this what not my intention to be honest :-).

I'd like to store (e.g. manually or by some other automation) secrets in SecretsManager (i.e. to not store secrets in Git), then optionally add a rotation lambda function to it. 
After that resource exists in AWS, I want to create a Crossplane `Secret` and have Crossplane reference the existing AWS resource and create a Kubernetes secret with the content of the secret.

**Comment by MisterMX** [comment]
So what you describe could be solved by external-secrets-controller, right?

What I could imagine is to add an option `syncFromExternal` to Crossplane's SecretsManager to sync a K8s to an AWS secret. But I'm not sure if this would follow the idea of Crossplane which aims to have K8s as a source of truth.

@negz any comments on that?

**Comment by haarchri** [comment]
we will follow with #655  the late-init feature was implemented with #668
