### ISSUE TITLE
Define a release cadence

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#644]
### What problem are you facing?

Crossplane has its own [release cadence](https://crossplane.io/docs/master/reference/release-cycle.html) but that doesn't bind the providers. We need a similar mechanism for provider-aws.

### How could Crossplane help solve your problem?

So far, we released providers when we released a new Crossplane version. We could continue doing that or have a separate release cycle but it's important to document it in the README.md.

I'd suggest **monthly** releases for provider-aws until we reach a level where most of the PRs are not support for new resource types.

**Comment by haarchri** [comment]
closed this issue because of #878 - feel free to reopen
