### ISSUE TITLE
Key (kms.aws.crossplane.io) is not creating new resources

### ISSUE THREAD

**Issue by EladDolev** [crossplane/provider-aws#647]
### What happened?

Unable to create a new KMS key, not even with the committed example. Getting `failed to describe Key: NotFoundException: Invalid keyId dev-key`

If I set `metadata.name` to an already existing KeyId, it seems to work fine, and the same if I use an arbitrary name and set the `crossplane.io/external-name` annotation to an already existing KeyId

### How can we reproduce it?
Apply the example from `examples/kms/key.yaml`

### What environment did it happen in?
Crossplane version: v1.2.0
AWS provider: 0.18.0
Kubernetes version: v1.18.16
Kubernetes distribution: kops
OS: 20.04.2 LTS (Focal Fossa)
Kernel: 5.4.0-1038-aws

**Comment by bandesz** [comment]
Same here, tried to use the resource in a composition:

```
  Warning  CannotObserveExternalResource  47s (x8 over 2m44s)  managed/key.kms.aws.crossplane.io  failed to describe Key: NotFoundException: Invalid keyId kms-test-cjs55-gzftn
```

Crossplane version: v1.2.1
AWS Provider: 0.18.0
