### ISSUE TITLE
ACM-PCA Typo - SUBORINATE vs SUBORDINATE

### ISSUE THREAD

**Issue by RafalMaleska** [crossplane/provider-aws#651]
### What happened?

when creating an aws acm-pca certificate authority SUBORDINATE getting: 

`Unsupported value: "SUBORDINATE": supported values: "ROOT", "SUBORINATE"`

### How can we reproduce it?
One can find the Bug here: 

https://github.com/crossplane/provider-aws/blob/57f44d68092afe6f6a04d4b529a61357da1ce2d9/package/crds/acmpca.aws.crossplane.io_certificateauthorities.yaml#L193 

### What environment did it happen in?
AWS
Crossplane: 1.1

**Comment by hasheddan** [comment]
@RafalMaleska thanks for noticing this! Are you interested in opening a fix?

**Comment by RafalMaleska** [comment]
@hasheddan 

thanks for encouraging - created a PR. hope its right
