### ISSUE TITLE
RDSInstance: missing masterUsername in secret

### ISSUE THREAD

**Issue by nbenaglia** [crossplane/provider-aws#658]
What happened?

In a RDSInstance manifest I specified the writeConnectionSecretToRef as specified in API (https://doc.crds.dev/github.com/crossplane/provider-aws/database.aws.crossplane.io/RDSInstance/v1beta1@v0.16.0#spec-writeConnectionSecretToRef):

apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
  ...
   forProvider:
  ...
  masterUsername: admin
  ...
  writeConnectionSecretToRef:
      name: {{ .Release.Name }}-credentials
      namespace: {{ .Release.Namespace}}

The created secret doesn't contain the masterUsername as instead expected:

{
  "endpoint": "...",
  "password": "...",
  "port": "..."
}

What environment did it happen in?

Crossplane version: v1.2.1
crossplane/provider-aws-controller: v0.18.0

**Comment by muvaf** [comment]
That's weird. The code sets it [here](https://github.com/crossplane/provider-aws/blob/5a380ad/pkg/controller/database/rdsinstance.go#L179). Are you able to reproduce this consistently?

**Comment by nbenaglia** [comment]
Unfortunately I could not replicate this weird problem.
I close this issue.

**Comment by bplotnick** [comment]
I'm think I'm seeing this. If you delete the secret object, the reconciliation will add it back, but only with endpoint and port.

**Comment by afirth** [comment]
Seeing this too. Can I
/reopen?
