### ISSUE TITLE
HostedZoneStatus (atProvider.hostedZone.id) returning a prefix along with HostedZoneId 

### ISSUE THREAD

**Issue by librannk** [crossplane/provider-aws#682]
while working on the creation of the hosted zone, was trying to get hosted zone id HostedZoneStatus (atProvider.hostedZone.id), 
found that it is returning a prefix along with the id  something like below, now this makes it less useful for further services which only requires the ID and currently transforms are limited hence string transformations are not supported hence removing this is not possible to fetch the id alone.

Hosted Zone Id:         /hostedzone/Z13322DRRSS

i see in the code below 
https://github.com/crossplane/provider-aws/blob/master/pkg/clients/hostedzone/hostedzone.go

// IDPrefix is the prefix of the actual ID that's returned from GET call.const IDPrefix = "/hostedzone/"

can this be removed from HostedZoneStatus (as currently adding some prefix using transform is still possible)  or at least made "hostedzone/" thereby would solve the issue of using hosted zone temp as seen below extra / is making problem.

below "/" infront of hosted zone needs to be removed or preferably /hostedzone/ should be removed from status 
"Resource": [                                                                                                               
         "arn:aws:route53:::/hostedzone/Z00151212Z97ZJCPKUPPH"                                                                     
      ]

**Comment by martin-ducar-gd** [comment]
Plz see https://github.com/crossplane/provider-aws/pull/683 for draft of idea for the fix not sure if this is the way to go but it feels like there are other objects/fields suffering same issues. either a complicated transformation functions need to be in place or compatibility fields or referencing fileds in other Objects. Simmilar problem can be seen here: https://github.com/crossplane/provider-aws/issues/628

**Comment by haarchri** [comment]
@martin-ducar-gd is https://github.com/crossplane/crossplane/pull/2633 an option for this ? Will be part of Crossplane 1.6.0

**Comment by haarchri** [comment]
In compositions we can use trim to get the correct ID only If needed
