### ISSUE TITLE
Can't delete SFN activities and state machines

### ISSUE THREAD

**Issue by negz** [crossplane/provider-aws#725]
### What happened?

When I delete an `Activity` or a `StateMachine` I see an error like the following:

```
  Warning  CannotObserveExternalResource  37s (x901 over 16h)  managed/statemachine.sfn.aws.crossplane.io  failed to describe StateMachine: StateMachineDoesNotExist: State Machine Does Not Exist: 'arn:aws:states:us-east-1:609897127049:stateMachine:sample-statemachine'
```

It seems like we're trying to ignore the case where `Observe` reports that the resource was not found - I suspect we're ignoring the wrong error.

https://github.com/crossplane/provider-aws/blob/7b5b5fca/pkg/controller/sfn/statemachine/zz_controller.go#L84

### How can we reproduce it?

```console
kubectl apply -f examples/sfn
# Wait for them to become ready...
kubectl delete -f examples/sfn
```

### What environment did it happen in?
provider-aws 7b5b5fca0e34b7f1d8e33d7feb8b63132e14b41a

**Comment by haarchri** [comment]
@negz  i added MR #730  changed the yaml for code-generator - now SFN stuffs are removed in k8s - feel free to test it ;)
