### ISSUE TITLE
Implement EBS volumes

### ISSUE THREAD

**Issue by mzingarelli** [crossplane/provider-aws#739]
### What problem are you facing?

There are some cases where EBS volumes need to be provisioned in a manner that the in-tree `aws-ebs` storage class or csi driver cannot. An example would be using different kms keys for different volumes. Currently the `aws-ebs-csi-driver` uses the same kms key for all volumes created with it

### How could Crossplane help solve your problem?

We could use a composite resource definition to create the kms key and volume in a single shot. Static storage provisioning could then be used to create the persistent volume from the ebs volume id

**Comment by robsclark** [comment]
@mzingarelli can we close this issue per @haarchri or is it still to be resolved?

**Comment by haarchri** [comment]
@robsclark the MR is Open - needs review & after that i can rebase
