### ISSUE TITLE
Implement transit gateway vpc attachment

### ISSUE THREAD

**Issue by mqxter** [crossplane/provider-aws#750]
### What problem are you facing?
Transit gateway vpc attachment is not implemented. 
In my case i want to attach an existing transit gateway to the new vpc created by crossplane in order to later specify a route in to the transit gateway in the route tables. 
 
### How could Crossplane help solve your problem?
implement creation of transit gateway vpc attachment
thanks guys

**Comment by haarchri** [comment]
implemented by #831  and included in provider-aws v0.22.0
