### ISSUE TITLE
make services fails with can not run goimports

### ISSUE THREAD

**Issue by luebken** [crossplane/provider-aws#788]
### What happened?

I've cloned this repo. Ran `make submodules` and ran `mkdir .work`.

`make services` fails with `Error: cannot run goimports: exit status 2`

```console
$ make services SERVICES=es
Cloning into 'code-generator'...
remote: Enumerating objects: 1997, done.
remote: Counting objects: 100% (742/742), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 1997 (delta 582), reused 533 (delta 498), pack-reused 1255
Receiving objects: 100% (1997/1997), 1.59 MiB | 10.67 MiB/s, done.
Resolving deltas: 100% (1147/1147), done.
Note: switching to 'cac5654b7bb64c8f754ad9af01799ef70d9541b6'.
HEAD is now at cac5654 Add a new config to override `kubebuilder:printcolumn` priority (#86)
08:29:50 [ .. ] Generating es controllers and CRDs
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/spf13/cobra v1.1.1
go: downloading golang.org/x/mod v0.4.1
go: downloading k8s.io/apimachinery v0.20.1
go: downloading github.com/iancoleman/strcase v0.1.3
go: downloading github.com/operator-framework/api v0.6.0
go: downloading github.com/aws/aws-sdk-go v1.37.4
go: downloading github.com/gertd/go-pluralize v0.1.1
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/dlclark/regexp2 v1.4.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading k8s.io/api v0.20.1
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading k8s.io/client-go v0.20.1
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading github.com/google/gofuzz v1.1.0
go: downloading k8s.io/klog v1.0.0
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.0.2
go: downloading golang.org/x/sys v0.0.0-20201112073958-5cba982894dd
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading k8s.io/klog/v2 v2.4.0
go: downloading golang.org/x/net v0.0.0-20201110031124-69a78807bb2b
go: downloading github.com/json-iterator/go v1.1.10
go: downloading k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading k8s.io/utils v0.0.0-20201110183641-67b214c5f920
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading golang.org/x/crypto v0.0.0-20201002170205-7f63de1d35b0
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading github.com/go-logr/logr v0.3.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading golang.org/x/text v0.3.4
go: downloading github.com/googleapis/gnostic v0.5.1
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/golang/protobuf v1.4.3
go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
go: downloading github.com/jmespath/go-jmespath v0.4.0
Error: cannot run goimports: exit status 2
exit status 1
make: *** [services] Error 1
```

Note that running `goimports` directly works: 

```
$ goimports --help
usage: goimports [flags] [path ...]
  -cpuprofile string
    	CPU profile output
  -d	display diffs instead of rewriting file
 ...
```
 
### What environment did it happen in?
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mdl/Library/Caches/go-build"
GOENV="/Users/mdl/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mdl/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mdl/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mdl/workspace/crossplane-github/provider-aws/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0t/hjtdjttj2sl9xkz4l04trssm0000gn/T/go-build1164609533=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by luebken** [comment]
Note that I'm unfamiliar with https://github.com/upbound/build/.

**Comment by luebken** [comment]
Note that it did generate the following files: 

	new file:   apis/elasticsearchservice/v1alpha1/zz_doc.go
	new file:   apis/elasticsearchservice/v1alpha1/zz_elasticsearch_domain.go
	new file:   apis/elasticsearchservice/v1alpha1/zz_enums.go
	new file:   apis/elasticsearchservice/v1alpha1/zz_groupversion_info.go
	new file:   apis/elasticsearchservice/v1alpha1/zz_outbound_cross_cluster_search_connection.go
	new file:   apis/elasticsearchservice/v1alpha1/zz_package.go
	new file:   apis/elasticsearchservice/v1alpha1/zz_types.go
	new file:   pkg/controller/elasticsearchservice/elasticsearchdomain/zz_controller.go
	new file:   pkg/controller/elasticsearchservice/elasticsearchdomain/zz_conversions.go
	new file:   pkg/controller/elasticsearchservice/outboundcrossclustersearchconnection/zz_controller.go
	new file:   pkg/controller/elasticsearchservice/outboundcrossclustersearchconnection/zz_conversions.go
	new file:   pkg/controller/elasticsearchservice/package/zz_controller.go
	new file:   pkg/controller/elasticsearchservice/package/zz_conversions.go

**Comment by luebken** [comment]
`make generate` produces: 

```
10:19:52 [ .. ] go generate darwin_arm64
...
/Users/mdl/workspace/crossplane-github/provider-aws/apis/elasticsearchservice/v1alpha1/zz_elasticsearch_domain.go:76:2: unknown type CustomElasticsearchDomainParameters
/Users/mdl/workspace/crossplane-github/provider-aws/apis/elasticsearchservice/v1alpha1/zz_outbound_cross_cluster_search_connection.go:42:2: unknown type CustomOutboundCrossClusterSearchConnectionParameters
/Users/mdl/workspace/crossplane-github/provider-aws/apis/elasticsearchservice/v1alpha1/zz_package.go:43:2: unknown type CustomPackageParameters
Error: not all generators ran successfully
...
```

**Comment by ulucinar** [comment]
Hi @luebken,
A quick remedy to unblock you seems to be the following:
```
mkdir -p pkg/controller/es
mkdir -p apis/es/v1alpha1
make services SERVICES=es
```
I did not check the underlying reason though yet.

**Comment by ulucinar** [comment]
> `make generate` produces:
> 
> ```
> 10:19:52 [ .. ] go generate darwin_arm64
> ...
> /Users/mdl/workspace/crossplane-github/provider-aws/apis/elasticsearchservice/v1alpha1/zz_elasticsearch_domain.go:76:2: unknown type CustomElasticsearchDomainParameters
> /Users/mdl/workspace/crossplane-github/provider-aws/apis/elasticsearchservice/v1alpha1/zz_outbound_cross_cluster_search_connection.go:42:2: unknown type CustomOutboundCrossClusterSearchConnectionParameters
> /Users/mdl/workspace/crossplane-github/provider-aws/apis/elasticsearchservice/v1alpha1/zz_package.go:43:2: unknown type CustomPackageParameters
> Error: not all generators ran successfully
> ...
> ```

For the missing Custom... type error, did you follow the instructions here?:
https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md#crossplane-code-generation

We need to add initially empty `Custom<CRDName>Parameters` structs to get the `make generate` target run successfully.

**Comment by muvaf** [comment]
I tried this in my local and it seems that there is a resource called `Package` which causes controller Go files to have `package package` statement, which wouldn't compile. A quick workaround would be to ignore this type for the time being. You can delete all generated files and create `elasticsearchservice/v1alpha1/generator-config.yaml` with the following content:
```yaml
ignore:
  resource_names:
    - Package
```

Another bug I discovered is that `es` is shorthand name for `elasticsearchservice` but for some reason ACK doesn't recognize the `elasticsearchservice/v1alpha1/generator-config.yaml` unless you use `elasticsearchservice` as service name, probably because the logic that looks for config file runs before everything and takes the string you give into account, which is a bug we can report in ACK repo. For now, having that file and running `make services SERVICES=elasticsearchservice` would work. Then you can add more ignore statements for CRDs you don't want to deal with as you'd like.

**Comment by luebken** [comment]
Following the advice I've:
* [Ignored the Package Resource](https://github.com/luebken/crossplane/commit/8b5782af4ed0b80a63602e29b2b3779195b0ee32)
* [Generated the other Resources](https://github.com/luebken/crossplane/commit/26450471e1213c6270726388920a9e41c3e8ebdf)

**Comment by luebken** [comment]
I was able to: 
* [Add the missing parameter type](https://github.com/luebken/provider-aws/pull/1/commits/4080d54e79bc60fc16ef2dfb1e5966abf8ca0447)
* [Generate the CRDs](https://github.com/luebken/provider-aws/pull/1/commits/5bd25685872584250e7aca4c7f2ffca71e7730ca)

**Comment by luebken** [comment]
Closing as I am not actively working on this.
