### ISSUE TITLE
Deduce unspecified Quantity from len(Items) in complex nested types of CloudFront Distribution

### ISSUE THREAD

**Issue by ulucinar** [crossplane/provider-aws#789]
### What problem are you facing?

Currently users of the CloudFront Distribution MR have to specify the length of the `OriginSslProtocols.Items` in `OriginSslProtocols.Quantity`. There are also other similar complex "array" types.

### How could Crossplane help solve your problem?

We may extend the `preCreate` and `preUpdate` logic [here](https://github.com/crossplane/provider-aws/blob/c8cc67e9c2320be34292efa8d232b7f58f071684/pkg/controller/cloudfront/distribution/setup.go#L81) and [here](https://github.com/crossplane/provider-aws/blob/c8cc67e9c2320be34292efa8d232b7f58f071684/pkg/controller/cloudfront/distribution/setup.go#L155), respectively, to include similar complex types.

**Comment by haarchri** [comment]
Fixed by #1186
