### ISSUE TITLE
Ability to create RDSInstance from snapshot

### ISSUE THREAD

**Issue by mzingarelli** [crossplane/provider-aws#813]
### What problem are you facing?

When creating a new `RDSInstance`, we would like to create the databases from an existing snapshot.
This issue relates #227 but takes it a step further by adding the ability to restore any database type from a snapshot (aswell as from an S3 bucket)

Something along the lines of:

```
spec:
  forProvider:
    fromBackup:
     snapShotIdentifier:
       Id: my-shapshot-id
//     s3: 
//       bucket: mybucket
//       prefix: prefix
//      role: ....
```
### How could Crossplane help solve your problem?

Without this feature, we need to manually `pg_dump` and `pg_restore` the database contents manually into a Crossplane managed database.

This feature would help us quickly spin up managed `RDSInstance` from snapshot

**Comment by muvaf** [comment]
https://github.com/crossplane/provider-aws/pull/770 implements restoration from S3. I think after that's merged, it'd be trivial to add other snapshot sources like [PointInTime](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceToPointInTime.html) and [DBSnapshot](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceFromDBSnapshot.html).

@mzingarelli are these the ones that'd work for your use case?

**Comment by jbhennin** [comment]
@muvaf we are very interested in being able to restore from a DBSnapshot and from PointInTime.    Note, that this should be supported for Cluster and Instance

**Comment by danports** [comment]
Now that #770 has been merged, I think I'll take a crack at this one next, since I could use it in my environment too.

**Comment by danports** [comment]
https://github.com/crossplane/provider-aws/pull/1087 has been merged, which addresses snapshot restores for DB instances. Point in time restores and DB cluster restores are still open issues.

**Comment by jbhennin** [comment]
@danports do you know the open issue for DB Cluster and DBInstance?

**Comment by haarchri** [comment]
follow up in #1085 and #1214
