### ISSUE TITLE
Add support for taints and spot instances for node groups

### ISSUE THREAD

**Issue by rotemjac** [crossplane/provider-aws#815]
### What resource do you need?
Support for taints and spot instances in EKS node group.

### What is your use case?

Simple EKS deployment with Taints for my database layer and Spot instances for cost saving.

### Relevant links:

AWS:
https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html
https://aws.amazon.com/getting-started/hands-on/amazon-eks-with-spot-instances/

Terraform:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#taint-configuration-block
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#capacity_type

**Comment by janwillies** [comment]
this depends on #383 as the eks controller is not yet code generated
