### ISSUE TITLE
Fill random available zones if no subnet availability zone is provided in the Subnet resource

### ISSUE THREAD

**Issue by vadasambar** [crossplane/provider-aws#84]
Can we add random availability zones as defaults based on the region selected in `EKSClusterClass` and `Provider` if no `availabilityZone` is provided for in the `Subnet` resource.

For example if the region in `Provider` and `EKSClusterClass` is `us-east-1`, `Subnet` resource's `availabilityZone` can be populated with `us-east-1a` or `us-east-1b` randomly based on the availability zones for the region if the `availabilityZone` field is empty or not present. 

Upsides
----------
- One less thing to think about if I don't care about the availability zones of a subnet

Downsides
------------
- Might lead to confusion

**Comment by hasheddan** [comment]
@vadasambar thanks for raising this issue to improve user experience :) I believe the `availabilityZone` field is currently required on `Subnet` resources. The AWS API states that they will [select one for you](https://github.com/crossplaneio/stack-aws/blob/959e192a3c5ac4487bf38bda77142a4d3524d135/apis/network/v1alpha3/subnet_types.go#L56) if the field is not defined on creation. Are you suggesting that we make the `availabilityZone` field optional, and then [late initialize](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#pointer-types-and-markers) it if a value is not provided and AWS picks one?

**Comment by vadasambar** [comment]
@hasheddan yes! We should let `availabilityZone` be optional and allow AWS to pick one for us if no availability zone is specified.

**Comment by hasheddan** [comment]
@vadasambar Great! When the `EKSCluster` resource is moved to `v1beta1` this should be the experienced behavior because it most closely reflects the AWS API. I will keep this issue open to denote this specific desired behavior. `v1beta1` migration is loosely tracked by #24 but there will likely be another more focused issue opened when the work is being started. Thank you for raising this!

**Comment by muvaf** [comment]
@hasheddan is this still relevant?
