### ISSUE TITLE
AWS Api Gateway Rest API

### ISSUE THREAD

**Issue by jbuettnerbild** [crossplane/provider-aws#845]
At the moment only HTTP and WEBSOCKET are supported.

For my usecase i need a AWS **REST** Api Gateway. 
Further: The Documentation of the Api Gateway is very bad (https://doc.crds.dev/github.com/crossplane/provider-aws/apigatewayv2.aws.crossplane.io/API/v1alpha1@v0.19.1)
It will be very helpful to see the available options. 
For example: for the required parameters _protocolType_ something like _Must be one of [HTTP, WEBSOCKET]_

**Comment by muvaf** [comment]
@jbuettnerbild It seems these are the only types that are currently supported by AWS, see the [AWS CLI command doc](https://docs.aws.amazon.com/cli/latest/reference/apigatewayv2/create-api.html). It'd be more helpful if you can share commands, scripts or Terraform HCLs you use to achieve your goals so that we can see which resources and parameters are needed.

**Comment by jbuettnerbild** [comment]
hi @muvaf.
in my case i use a REST Api Gateway to use a AWS Services (S3). I saw that this will also works with WEbSocket Api but i have no idee how to do that with crossplane. I saw the apigateway2 example: https://github.com/crossplane/provider-aws/blob/master/examples/apigatewayv2/integration.yaml
and maybe its just the integrationType but the documentation is very bad (empty): https://doc.crds.dev/github.com/crossplane/provider-aws/apigatewayv2.aws.crossplane.io/Integration/v1alpha1@v0.19.1#spec-forProvider-integrationType  

Over the AWS Console you have four options.
<img width="941" alt="Bildschirmfoto 2021-10-06 um 13 16 08" src="https://user-images.githubusercontent.com/34340440/136192743-adbd286c-d494-4031-9c48-60699c0a858f.png">

Currently i did this with terraform --> https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api
See the Note: Amazon API Gateway Version 1 resources are used for creating and deploying REST APIs

A better dokumentation or a example for AWS services over Websocket Api Gateway would be helpfull.

**Comment by apmartins85** [comment]
Hi folks .. We are actually facing the same issue! Is it this "issue" on crossplane roadmap?

**Comment by muvaf** [comment]
It seems like we need support for `apigateway` API group. The current one is `apigatewayv2` which doesn't include that. You can take a stab at it by following the code generation guide [here](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md) or try [jet-based AWS provider](https://github.com/crossplane-contrib/provider-jet-aws/releases/tag/v0.4.0-preview) which has support for all types Terraform does.

**Comment by aleicher** [comment]
`apigateway2` API group only supports the HTTP API Gateway. Our usecase would be to provision a private REST API Gateway in our VPC. REST API Gateway types are all part of the `apigateway` API group in AWS. So I guess following the code generation path mentioned by @muvaf would be the way to go, to add support for the `apigateway` group in provider-aws.

**Comment by aleicher** [comment]
maybe interesting for @apmartins85 and @jbuettnerbild check out the awesome provider-jet-aws (leveraging terraform under the hood).

It has coverage for both apigateway API versions, and from looking at the code in https://github.com/crossplane-contrib/provider-jet-aws it should provide support for the REST APIGateway in v0.4.0-preview according to https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/apigateway.aws.jet.crossplane.io/RestAPI/v1alpha1@v0.4.0-preview

so if you need it earlier than it can be made into the provider-aws maybe you give the provider-jet-aws a spin. I guess I'll try it for my use case

**Comment by haarchri** [comment]
implemented with #1230
