### ISSUE TITLE
Split Makefile `GENERATED_SERVICES` into one line per service to reduce the number of merge conflicts

### ISSUE THREAD

**Issue by chlunde** [crossplane/provider-aws#861]
### What problem are you facing?
We have to rebase for every new service using code gen when two PRs are in flight at the same time. Additionally, some services like ec2 has been missing from the Makefile.

### How could Crossplane help solve your problem?
We could reduce the likelyhood of merge conflict by:
#### A) Removing `GENERATED_SERVICES` and use find or similar to generate the list
```
find . -name generator-config.yaml | cut -d/ -f 3
apigatewayv2
dynamodb
ec2
efs
kms
rds
secretsmanager
sfn
cloudfront
lambda
servicediscovery
route53resolver
kafka
docdb
transfer
elasticache
```

#### B) One line per entry (using `define`?)
https://stackoverflow.com/a/649462

**Comment by ajesk** [comment]
Going to take a look into this
