### ISSUE TITLE
Excluded Resources are being included in CRDs

### ISSUE THREAD

**Issue by AaronME** [crossplane/provider-aws#876]
### What happened?
CRDs are not honoring the list of ignored-resources in `generator-config.yaml`

We can see this in the SecurityGroup resource currently on `master`:

SecurityGroup is a managed resource in [ec2/v1beta1](https://github.com/crossplane/provider-aws/blob/6f7e613d86e181b2042b1aa8d1ba33954850359a/apis/ec2/v1beta1/securitygroup_types.go#L250).
SecurityGroup is only a type in [ec2/v1alpha1](https://github.com/crossplane/provider-aws/blob/6f7e613d86e181b2042b1aa8d1ba33954850359a/apis/ec2/v1alpha1/zz_types.go#L2428).

The [ec2/v1alpha1/generator-config.yaml](https://github.com/crossplane/provider-aws/blob/6f7e613d86e181b2042b1aa8d1ba33954850359a/apis/ec2/v1alpha1/generator-config.yaml#L34) specifies SecurityGroup as an ignored resource.

However [both](https://github.com/crossplane/provider-aws/blob/6f7e613d86e181b2042b1aa8d1ba33954850359a/package/crds/ec2.aws.crossplane.io_securitygroups.yaml#L21) [versions](https://github.com/crossplane/provider-aws/blob/6f7e613d86e181b2042b1aa8d1ba33954850359a/package/crds/ec2.aws.crossplane.io_securitygroups.yaml#L47) are present in the CRD. 

When the storageVersion is a managed-resource, this is a minor bug. When the storageVersion is the type, as in https://github.com/crossplane/provider-aws/pull/859, it can cause the resource to lose the status fields which crossplane requires.

### How can we reproduce it?
1. Checkout https://github.com/crossplane/provider-aws/pull/859
2. Run `make generate` and note that the CRD contains two different specs for v1alpha1 and v1beta1.
3. The v1beta1 resource is missing status fields, and is the storageVersion.
4. Apply the CRDs to the cluster and create a v1alpha1 route.
5. `kubectl get route.ec2.aws.crossplane.io` will be missing status fields:
```bash
% kubectl get route.ec2.aws.crossplane.io
NAME      AGE
example   96s
```
6. The status is missing because the CRD for Route contains a storage version which does not supply the crossplane-required status fields.

### What environment did it happen in?
Kind cluster
Kubernetes version:
```bash
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-25T19:57:36Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by muvaf** [comment]
> We could mark all generated types with skipversion to keep them out of CRDs. But this seems unelegant.

@AaronME I just tested this one and it seems like the only viable option here. We need to add `// +kubebuilder:skipversion` to [here](https://github.com/aws-controllers-k8s/code-generator/blob/926fa23/templates/crossplane/apis/type_def.go.tpl#L2).

For other options, having the information of a collision is a hard one for ACK since the types are generated by a different mechanism than CRD file and even if we take it from the user, I'm not sure if it's worth opening another config interface in `generator-config.yaml` as you said.

I can work on it only next week. @AaronME @haarchri If anyone is interested in opening a PR to ACK, it'd be great.

**Comment by AaronME** [comment]
@muvaf Opened https://github.com/aws-controllers-k8s/code-generator/pull/236
