### ISSUE TITLE
Launch new EC2 instance in VPC

### ISSUE THREAD

**Issue by jambu** [crossplane/provider-aws#877]
I cant find the composition for launching standalone ec2 instance(s) in a VPC as opposed to EKS.
I assumed this would be there as a basic resource, but not sure if I am missing this listed somewhere.

**Comment by haarchri** [comment]
can you have a look here? https://github.com/crossplane/provider-aws/blob/master/examples/ec2/instance.yaml

**Comment by dolisss** [comment]
I am trying to create a standalone instance using:https://github.com/crossplane/provider-aws/blob/master/examples/ec2/instance.yaml but that doesn't work for me. It throws and error: Warning  CannotResolveResourceReferences  4m16s (x2306 over 37h)  managed/instance.ec2.aws.crossplane.io  cannot resolve references: spec.forProvider.securityGroupIDs: cannot get referenced resource: SecurityGroup.ec2.aws.crossplane.io "crossplane" not found




@jambu @haarchri can you help me here? 

instance.yaml:

apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: sample-instance
spec:
  forProvider:
    region: us-west-1
    imageId: ami-0dc2d3e4c0f9ebd18
    securityGroupRefs:
      - name: crossplane
    subnetIdRef:
      name: crossplane-1a
  providerConfigRef:
    name: awsconfig

**Comment by haarchri** [comment]
@dolisss  you need to setup also a securityGroup with name crossplane via crossplane then the resolver is working https://github.com/crossplane/provider-aws/blob/master/examples/ec2/securitygroup.yaml

**Comment by dolisss** [comment]
@haarchri Thank you for your quick response!!
Quick question: the same is applicable to the subnet? 
And is there a way cross-plane resolves the existing AWS resources like SG, subnet, VPC?

**Comment by haarchri** [comment]
you can use the fields without ref or selector and hardcode the ids =) https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/Instance/v1alpha1@v0.21.0#spec-forProvider-securityGroupIds

**Comment by dolisss** [comment]
@haarchri That works! Thanks a lot!
