### ISSUE TITLE
VPC Endpoints

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#934]
### What problem are you facing?

No vpc endpoints which is useful for enabling no auth access to buckets.
Like this: https://aws.amazon.com/premiumsupport/knowledge-center/s3-private-connection-no-authentication/

### How could Crossplane help solve your problem?

VPC Endpoint resource

**Comment by haarchri** [comment]
We have a Open PR for VPC Endpoint: https://github.com/crossplane/provider-aws/pull/817
