### ISSUE TITLE
Release v0.21.0 on November 16, 2021

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#947]
### Checklist

* [x] Create the new release branch with minor version, i.e. `release-0.21` for `v0.21.0`.
  * You can use the existing branch for patch releases.
* [x] Tag release by running `Tag` action in Github UI against release branch, i.e. `release-X` branch.
  * Use v-prefixed version, like `v0.21.0`, for both description and tag.
* [x] Run `CI` action against release branch.
* [x] Tag the next pre-release by running `Tag` action in Github UI against `master` branch, if it's not a patch release.
  * The tag should be `v0.22.0-rc.0` if you're releasing `v0.21.x`.
* [x] Validate that you can install the published version, basic sanity check.
* [x] Run `Promote` action to promote it in `alpha` channel if it's pre-`1.0`.
* [x] Use Github UI to generate release notes.
  * Make sure to scan all PRs marked with `breaking-change` and add instructions for users to handle them.
* [x] Create the next release issue with a title that has its date, **4 weeks** after the current release day.
* [x] Announce in Slack, Twitter etc.

**Comment by muvaf** [comment]
I have merged a couple of approved PRs and I was too fast that CI broke in master because we don't require PRs to be up-to-date. https://github.com/crossplane/provider-aws/pull/950 is opened to fix it.

We'll continue the release process once that PR is merged.

**Comment by haarchri** [comment]
@muvaf what is missing to create Release ? I can see that some Folks using 0.21.x ;)

**Comment by muvaf** [comment]
@haarchri It's the generated release notes in Github. Details are here: https://github.com/github/feedback/discussions/5975#discussioncomment-1660720

I guess I'll have to go with manual release notes until the issue is fixed.

**Comment by muvaf** [comment]
Done! https://github.com/crossplane/provider-aws/releases/tag/v0.21.0
