### ISSUE TITLE
RDSInstance keep getting configuring-enhanced-monitoring state

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#980]
### What happened?
 The resource are having more syncing than usual compared to the provider-aws version that i am using previously at 0.18. it keep getting configuring-enhanced-monitoring state to be updated again and again.

shown from my log:
```
test-mysqlinstance-knqk2-tsvkv        True    True     available                         mysql      5.7       14d
test-mysqlinstance-knqk2-tsvkv        True    True     available                         mysql      5.7       14d
test-mysqlinstance-knqk2-tsvkv        True    True     available                         mysql      5.7.33    14d
test-mysqlinstance-knqk2-tsvkv        True    False    available                         mysql      5.7.33    14d
test-mysqlinstance-knqk2-tsvkv        True    False    configuring-enhanced-monitoring   mysql      5.7.33    14d
test-postgresqlinstance-t9s4z-p4dd9   True    True     available                         postgres   12.7      14d
test-postgresqlinstance-t9s4z-p4dd9   True    True     available                         postgres   12.7      14d
test-postgresqlinstance-t9s4z-p4dd9   True    False    configuring-enhanced-monitoring   postgres   12.7      14d
test-postgresqlinstance-t9s4z-p4dd9   True    True     available                         postgres   12.7      14d
test-mysqlinstance-knqk2-tsvkv        True    False    configuring-enhanced-monitoring   mysql      5.7       14d
test-mysqlinstance-knqk2-tsvkv        True    False    configuring-enhanced-monitoring   mysql      5.7       14d
test-mysqlinstance-knqk2-tsvkv        True    False    configuring-enhanced-monitoring   mysql      5.7       14d
test-mysqlinstance-knqk2-tsvkv        True    False    configuring-enhanced-monitoring   mysql      5.7       14d
test-mysqlinstance-knqk2-tsvkv        True    False    configuring-enhanced-monitoring   mysql      5.7.33    14d
test-mysqlinstance-knqk2-tsvkv        True    True     modifying                         mysql      5.7.33    14d
test-postgresqlinstance-t9s4z-p4dd9   True    True     available                         postgres   12.7      14d
test-postgresqlinstance-t9s4z-p4dd9   True    True     available                         postgres   12.7      14d
test-postgresqlinstance-t9s4z-p4dd9   True    True     available                         postgres   12.7      14d
```

event logs:
```
14m         Normal    UpdatedExternalResource           rdsinstance/test-mysqlinstance-knqk2-tsvkv                                     Successfully requested update of external resource
4m30s       Warning   CannotUpdateManagedResource       rdsinstance/test-mysqlinstance-knqk2-tsvkv                                     Operation cannot be fulfilled on rdsinstances.database.aws.crossplane.io "test-mysqlinstance-knqk2-tsvkv": the object has been modified; please apply your changes to the latest version and try again
9m40s       Warning   CannotUpdateExternalResource      rdsinstance/test-mysqlinstance-knqk2-tsvkv                                     cannot modify RDS instance: InvalidDBInstanceState: Database instance is not in available state.
4m31s       Normal    SelectComposition                 mysqlinstance/test-mysqlinstance-knqk2                                         Successfully selected composition
30s         Normal    ComposeResources                  mysqlinstance/test-mysqlinstance-knqk2                                         Successfully composed resources
23m         Normal    UpdatedExternalResource           rdsinstance/test-postgresqlinstance-t9s4z-p4dd9                                Successfully requested update of external resource
4m41s       Warning   CannotUpdateExternalResource      rdsinstance/test-postgresqlinstance-t9s4z-p4dd9                                cannot modify RDS instance: InvalidDBInstanceState: Database instance is not in available state.
48m         Warning   CannotInitializeManagedResource   rdsinstance/test-postgresqlinstance-t9s4z-p4dd9                                cannot update RDS instance custom resource: Operation cannot be fulfilled on rdsinstances.database.aws.crossplane.io "test-postgresqlinstance-t9s4z-p4dd9": the object has been modified; please apply your changes to the latest version and try again
```

### How can we reproduce it?

This is my rdsinstance CR generated by the composition resource:
```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/external-name: test-mysqlinstance
  name: test-mysqlinstance-knqk2-tsvkv
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 20
    allowMajorVersionUpgrade: false
    applyModificationsImmediately: true
    autoMinorVersionUpgrade: true
    availabilityZone: us-east-1a
    backupRetentionPeriod: 1
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: true
    dbInstanceClass: db.t3.micro
    dbParameterGroupName: default.mysql5.7
    dbSubnetGroupName: testmysql.dbsubgrp
    dbSubnetGroupNameRef:
      name: testmysql.dbsubgrp
    deletionProtection: false
    enableCloudwatchLogsExports:
    - audit
    - error
    - slowquery
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mysql
    engineVersion: 5.7.33
    finalDBSnapshotIdentifier: test-1a14ad9235b2
    kmsKeyId: arn:aws:kms:us-east-1:123456789/xxxxxxxxxx
    licenseModel: general-public-license
    masterUsername: admin
    monitoringInterval: 0
    multiAZ: false
    port: 3306
    preferredBackupWindow: 14:49-15:19
    preferredMaintenanceWindow: mon:20:37-mon:21:07
    publiclyAccessible: false
    region: us-east-1
    skipFinalSnapshotBeforeDeletion: false
    storageEncrypted: true
    storageType: gp2
    vpcSecurityGroupIds:
    - sg-xxxxxxxxxxx
  providerConfigRef:
    name: aws-provider
  writeConnectionSecretToRef:
    name: test-mysqlinstance-knqk2
    namespace: crossplane-system
status:
  atProvider:
    dbInstanceArn: arn:aws:rds:us-east-1:123456789:db:test-mysqlinstance
    dbInstanceStatus: available
    dbParameterGroups:
    - dbParameterGroupName: default.mysql5.7
      parameterApplyStatus: in-sync
    dbResourceId: db-xxxxxxxxxx
    dbSubnetGroup:
      dbSubnetGroupDescription: Created by Crossplane
      dbSubnetGroupName: testmysql.dbsubgrp
      subnetGroupStatus: Complete
      subnets:
      - subnetAvailabilityZone:
          name: us-east-1a
        subnetIdentifier: subnet-xxxxxxxxxx
        subnetStatus: Active
      - subnetAvailabilityZone:
          name: us-east-1b
        subnetIdentifier: subnet-xxxxxxxxxx
        subnetStatus: Active
      vpcId: vpc-xxxxxxxxxx
    endpoint:
      address: test-mysqlinstance.xxx.us-east-1.rds.amazonaws.com
      hostedZoneId: xxxxxxxxxx
      port: 3306
    optionGroupMemberships:
    - optionGroupName: default:mysql-5-7
      status: in-sync
    pendingModifiedValues:
      pendingCloudwatchLogsExports: {}
    vpcSecurityGroups:
    - status: active
      vpcSecurityGroupId: sg-xxxxxxxxxx
  conditions:
  - lastTransitionTime: "2021-11-30T03:28:30Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-12-01T02:02:47Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

### What environment did it happen in?
Crossplane version: 1.5
Provider-aws: 0.21.2

**Comment by kelvinwijaya** [comment]
@chlunde 

I highly suspect that is because due to default integer value `monitoringInterval: 0` generated by composition trigger the update:

https://github.com/crossplane/provider-aws/blob/1e29728f989c14d07b5325e3cc4fa8d6d298c51a/pkg/controller/rds/dbinstance/zz_conversions.go#L366

**Comment by kelvinwijaya** [comment]
Hi @chlunde ,

Adding on the value from `rsp.DBInstances[0]` during the Update function.
Strangely there are bunch of *null* value in the **PendingModifiedValues** object

```
"PendingModifiedValues": {
		"AllocatedStorage": null,
		"BackupRetentionPeriod": null,
		"CACertificateIdentifier": null,
		"DBInstanceClass": null,
		"DBInstanceIdentifier": null,
		"DBSubnetGroupName": null,
		"EngineVersion": null,
		"IAMDatabaseAuthenticationEnabled": null,
		"Iops": null,
		"LicenseModel": null,
		"MasterUserPassword": null,
		"MultiAZ": null,
		"PendingCloudwatchLogsExports": null,
		"Port": null,
		"ProcessorFeatures": null,
		"StorageType": null
	},
```

And resulted in patch object generate from `GenerateModifyDBInstanceInput` function which also have bunch of *null* values:

```
{
	"DBInstanceIdentifier": "test-mysqlinstance",
	"AllocatedStorage": null,
	"AllowMajorVersionUpgrade": false,
	"ApplyImmediately": true,
	"AutoMinorVersionUpgrade": null,
	"AwsBackupRecoveryPointArn": null,
	"BackupRetentionPeriod": null,
	"CACertificateIdentifier": null,
	"CertificateRotationRestart": null,
	"CloudwatchLogsExportConfiguration": null,
	"CopyTagsToSnapshot": null,
	"DBInstanceClass": null,
	"DBParameterGroupName": null,
	"DBPortNumber": null,
	"DBSecurityGroups": null,
	"DBSubnetGroupName": null,
	"DeletionProtection": false,
	"Domain": null,
	"DomainIAMRoleName": null,
	"EnableCustomerOwnedIp": null,
	"EnableIAMDatabaseAuthentication": false,
	"EnablePerformanceInsights": null,
	"EngineVersion": null,
	"Iops": null,
	"LicenseModel": null,
	"MasterUserPassword": null,
	"MaxAllocatedStorage": null,
	"MonitoringInterval": 0,
	"MonitoringRoleArn": null,
	"MultiAZ": false,
	"NewDBInstanceIdentifier": null,
	"OptionGroupName": null,
	"PerformanceInsightsKMSKeyId": null,
	"PerformanceInsightsRetentionPeriod": null,
	"PreferredBackupWindow": null,
	"PreferredMaintenanceWindow": null,
	"ProcessorFeatures": null,
	"PromotionTier": null,
	"PubliclyAccessible": false,
	"ReplicaMode": "",
	"StorageType": null,
	"TdeCredentialArn": null,
	"TdeCredentialPassword": null,
	"UseDefaultProcessorFeatures": null,
	"VpcSecurityGroupIds": null
}
```

**Comment by kelvinwijaya** [comment]
Hi @chlunde @muvaf 

I think i found the issues. This happen while migration from 0.18 -> 0.21. Need you to cfm as well.

I tried creating new rdsinstance thru composition . For v0.21, it does not have field `monitoringInterval: 0` even after the late-initialization.
For v0.18 or below, rdsinstance will populate the field `monitoringInterval: 0` in spec.forProvider

When this happen, it will re-trigger reconciliation with `configuring-enhanced-monitoring` in the new provider release whenever it hit Update method.


Comparison:
provider v0.18 using  `github.com/aws/aws-sdk-go-v2 v0.23.0`
provider v0.21 using `github.com/aws/aws-sdk-go-v2/service/rds v1.9.0`

Somehow, i debug thru the code and notice `rds.IsUpToDate()` will always return `false` regardless if the resource has been created successfully and in **available** state: https://github.com/crossplane/provider-aws/blob/1e29728f989c14d07b5325e3cc4fa8d6d298c51a/pkg/controller/database/rdsinstance.go#L135


Another question would be why do we call` rds.LateInitialize() `twice in **Observe** method?https://github.com/crossplane/provider-aws/blob/1e29728f989c14d07b5325e3cc4fa8d6d298c51a/pkg/controller/database/rdsinstance.go#L122
And the same `LateInitialize()` will be triggered again inside `rds.IsUpToDate()` -> `CreatePatch()` https://github.com/crossplane/provider-aws/blob/1e29728f989c14d07b5325e3cc4fa8d6d298c51a/pkg/clients/rds/rds.go#L139

**Comment by danports** [comment]
I've run into this too after a recent provider update. It's pretty annoying. @kelvinwijaya Do you have a suggested patch that I can test? I need to recompile the provider anyway to verify some unrelated changes.

**Comment by danports** [comment]
![image](https://user-images.githubusercontent.com/8728855/147985755-1cd04957-67ac-4464-b4eb-284ee81f192d.png)
The events on this RDSInstance show just how incessant the unnecessary updates are - the instance is only in the available state for a minute or two before the provider updates it again. 🤦

**Comment by kelvinwijaya** [comment]
Hi @danports ,

Are this RDSInstance resource has been there prior to update, and after you update the provider-aws , this issue pop-up?

In my case, I found that by removing the `monitoringInterval: 0` field from the existing RDSInstance manifest do helps. 
As for newer provider-aws version, this field is not required. And while keeping it will cause unnecessary api update that trigger state change to `configuring-enhanced-monitoring`

**Comment by danports** [comment]
Thanks for the tip @kelvinwijaya! I didn't have `monitoringInterval: 0` in my manifest, but removing that from the API server object via `kubectl edit` seems to have eliminated the constant `configuring-enhanced-monitoring` state changes. However, the provider continues requesting unnecessary updates to the RDS instance every couple of minutes - it's just that those updates now don't result in any state changes. So `monitoringInterval: 0` is only a partial fix.

**Comment by danports** [comment]
As you mentioned earlier, I had also noticed (on previous versions of the provider too) that `rds.IsUpToDate()` seems to be returning `false` all the time - I was thinking about adding logging to track down what exactly the provider thinks needs to be updated, but I haven't tried that yet. I think that issue may already be tracked (https://github.com/crossplane/provider-aws/issues/960).

**Comment by kelvinwijaya** [comment]
Hi @danports

Thanks for the update and happy to know it has been tracked in the separate ticket

**Comment by vivekjainx86** [comment]
Hi,
After upgrading provider-aws from v0.19 to v0.23, I faced same issue. Removing `monitoringInterval: 0`  field from existing RDSInstance object worked for me.
Thank you @kelvinwijaya for the temporary fix.

**Comment by erickfaustino** [comment]
Hi, everyone!
I ran into this problem, but my case is even worse, I think, because my DBs keep rebooting after the update of "Enhancing Monitoring", and I'm using argo, so it's not possible to delete the parameter `monitoringInterval`.
I've updated the `aws-provider` from `v0.24.1` to `v0.25.0` but it didn't help :( 
Does anyone has been able to fix this problem?

Thank you very much!

**Comment by haarchri** [comment]
for existing database you need to remove the field if it's already late-inited - did you tried provisioning a new database instance with provider version 0.25 ?

**Comment by erickfaustino** [comment]
@haarchri, thank you for your quick reply!
> for existing database you need to remove the field if it's already late-inited

Are you referring to the `monitoringInterval` field? 

No, I didn't tried to provision a new instance.

**Comment by haarchri** [comment]
Yes

**Comment by erickfaustino** [comment]
I have deleted the field from API server, but it's still happening.

**Comment by mqxter** [comment]
issue still persist on crossplanecontrib/provider-aws:v0.36.1
using the following manifest

apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: something
spec:
  forProvider:
    autoMinorVersionUpgrade: true
    availabilityZone: somewhere-1a
    dbClusterIdentifier: something-cluster
    dbInstanceClass: db.r5.large
    dbSubnetGroupName: primary-mysql-subnet-group
    enableCloudwatchLogsExports:
    - audit
    - error
    - slowquery
    enablePerformanceInsights: true
    engine: aurora-mysql
    kmsKeyID: some-key
    masterUsername: admin
    monitoringInterval: 1
    monitoringRoleARN: some-role
    multiAZ: false
    performanceInsightsKMSKeyID: some-key
    performanceInsightsRetentionPeriod: 7
    publiclyAccessible: false
    region: somewhere-1
    storageEncrypted: true
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: something
    namespace: default

using DBInstance in order to create an instance in a global aurora cluster
