### ISSUE TITLE
dbClusterParameterGroupNameRef missing in CRD definitiion

### ISSUE THREAD

**Issue by varunpalekar** [crossplane/provider-aws#984]
### dbClusterParameterGroupNameRef got missing in CRD definition of dbclusters.rds.aws.crossplane.io?

When deploying my menifiest file according to [docs](https://doc.crds.dev/github.com/crossplane/provider-aws/docdb.aws.crossplane.io/DBCluster/v1alpha1@v0.21.1)  we can use `dbClusterParameterGroupNameRef` to refer another cluster parameter group name from ref name, but when I used and try to deploy using helm chart giving following error

```
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DBCluster.spec.forProvider): unknown field "dbClusterParameterGroupNameRef" in io.crossplane.aws.rds.v1alpha1.DBCluster.spec.forProvider
```

### How can we reproduce it?

Please use dbClusterParameterGroupNameRef in defining resource dbclusters.rds.aws.crossplane.io

### What environment did it happen in?
Crossplane version: `1.5.0`

* Cloud provider or hardware configuration `provider-aws-v0.21.1`
* Kubernetes version (use `kubectl version`) `v1.20.7-eks-d88609`
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS

### Other info

I done some initial research and got to know `dbClusterParameterGroupNameRef ` definition also missing on CRD defined here https://github.com/crossplane/provider-aws/blob/master/package/crds/rds.aws.crossplane.io_dbclusters.yaml but also not defined, maybe need to define on CRD

**Comment by haarchri** [comment]
@varunpalekar for what resource you are looking for dbClusterParameterGroupNameRef ? 
in docs you referenced for docdb dbcluster and in crd you referenced rds dbcluster

for rds check: https://github.com/crossplane/provider-aws/blob/master/examples/rds/db-aurora-cluster.yaml#L16
for docdb check: https://github.com/crossplane/provider-aws/blob/master/examples/docdb/cluster.yaml#L12

**Comment by varunpalekar** [comment]
My bad, 
Thanks @haarchri for the help, now can I say can we use `dbClusterParameterGroupNameRef`  in `dbclusters.rds.aws.crossplane.io`

**Comment by haarchri** [comment]
@varunpalekar  added PR #987
